CREATE TABLE METADATA
(
  SIST_INDEKSERT   TIMESTAMP    NOT NULL
);

INSERT INTO METADATA (SIST_INDEKSERT)
VALUES (TO_TIMESTAMP('1970-01-01 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'));

CREATE TABLE OPPFOLGINGSBRUKER (
  PERSON_ID NUMBER NOT NULL,
  FODSELSNR VARCHAR(255) NOT NULL,
  ETTERNAVN VARCHAR(255),
  FORNAVN VARCHAR(255),
  NAV_KONTOR VARCHAR(255),
  FORMIDLINGSGRUPPEKODE VARCHAR(255),
  ISERV_FRA_DATO DATE,
  KVALIFISERINGSGRUPPEKODE VARCHAR(255),
  RETTIGHETSGRUPPEKODE VARCHAR(255),
  HOVEDMAALKODE VARCHAR(255),
  SIKKERHETSTILTAK_TYPE_KODE VARCHAR(255),
  FR_KODE VARCHAR(255),
  HAR_OPPFOLGINGSSAK VARCHAR(255),
  SPERRET_ANSATT VARCHAR(255),
  ER_DOED VARCHAR(255),
  DOED_FRA_DATO DATE,
  TIDSSTEMPEL DATE,
  PRIMARY KEY(PERSON_ID)
);

INSERT INTO OPPFOLGINGSBRUKER (PERSON_ID,FODSELSNR, ETTERNAVN, FORNAVN, FORMIDLINGSGRUPPEKODE, KVALIFISERINGSGRUPPEKODE, RETTIGHETSGRUPPEKODE, SPERRET_ANSATT, ER_DOED)
VALUES (1234567890,'01010101010', 'TESTESEN', 'TEST', 'ARBS', 'VARIG', 'IYT', 'N', 'N');