CREATE TABLE BRUKER_DATA (
  AKTOERID VARCHAR(20) NOT NULL,
  VEILEDERIDENT VARCHAR(20),
  TILDELT_TIDSPUNKT TIMESTAMP,
  PERSONID VARCHAR(20),
  PRIMARY KEY (AKTOERID));

CREATE TABLE AKTOERID_TO_PERSONID (
AKTOERID VARCHAR(20) NOT NULL,
 PERSONID VARCHAR(29) NOT NULL,
  PRIMARY KEY (AKTOERID));


INSERT INTO AKTOERID_TO_PERSONID VALUES ('11111111', '1234567890');