CREATE TABLE ARBEIDSLISTE (
  AKTOERID                     VARCHAR2(20) NOT NULL,
  SIST_ENDRET_AV_VEILEDERIDENT VARCHAR2(20),
  KOMMENTAR                    VARCHAR2(1000),
  FRIST                        TIMESTAMP,
  ENDRINGSTIDSPUNKT            TIMESTAMP,
  PRIMARY KEY (AKTOERID)
);

INSERT INTO BRUKER_DATA
(
  AKTOERID,
  VEILEDERIDENT,
  TILDELT_TIDSPUNKT,
  PERSONID,
  YTELSE,
  UTLOPSDATO,
  UTLOPSDATOFASETT,
  AAPMAXTID,
  AAPMAXTIDFASETT,
  OPPFOLGING,
  venterPaSvarFraBruker,
  venterPaSvarFraNav,
  IAVTALTAKTIVITET,
  NYESTEUTLOPTEAKTIVITET
)
VALUES
  (
    '9999999999991',
    'testident',
    SYSDATE,
    '9999',
    'AAP_UNNTAK',
    SYSDATE,
    NULL,
    SYSDATE,
    NULL,
    'J',
    SYSDATE,
    SYSDATE,
    NULL,
    NULL
  );

INSERT INTO ARBEIDSLISTE (
  AKTOERID,
  SIST_ENDRET_AV_VEILEDERIDENT,
  KOMMENTAR,
  FRIST,
  ENDRINGSTIDSPUNKT
)
VALUES (
  '9999999999991',
  'testident',
  'Dette er en kommentar',
  SYSDATE,
  SYSDATE
)
