ALTER TABLE BRUKER_DATA ADD NY_FOR_ENHET VARCHAR2(1) DEFAULT 'J';
UPDATE BRUKER_DATA SET NY_FOR_ENHET='N' WHERE VEILEDERIDENT IS NOT NULL;

-- To remove changes:
--
-- ALTER TABLE BRUKER_DATA
-- DROP (NY_FOR_ENHET);
