CREATE VIEW VW_OPPFOLGING_DATA AS(
SELECT 
  O.AKTOERID AS AKTOERID,
  O.OPPDATERT_KILDESYSTEM AS OPPDATERT_KILDESYSTEM, 
  O.OPPDATERT_PORTEFOLJE AS OPPDATERT_PORTEFOLJE, 
  O.NY_FOR_VEILEDER AS NY_FOR_VEILEDER,
  O.VEILEDERIDENT AS VEILEDERIDENT,
  O.OPPFOLGING AS OPPFOLGING,
  'OPPFOLGING_DATA' AS KILDE
FROM OPPFOLGING_DATA O
UNION
SELECT 
  BD.AKTOERID AS AKTOERID,
  BD.TILDELT_TIDSPUNKT AS OPPDATERT_KILDESYSTEM, 
  NULL AS OPPDATERT_PORTEFOLJE, 
  BD.NY_FOR_VEILEDER AS NY_FOR_VEILEDER,
  BD.VEILEDERIDENT AS VEILEDERIDENT,
  BD.OPPFOLGING AS OPPFOLGING,
  'BRUKER_DATA' AS KILDE
FROM BRUKER_DATA BD
WHERE BD.AKTOERID IS NOT NULL
  AND BD.AKTOERID NOT IN (SELECT AKTOERID FROM OPPFOLGING_DATA));

-- To remove changes:
--
-- DROP VIEW VW_OPPFOLGING_DATA;