CREATE TABLE TEST_OPPFOLGINGSBRUKER (
  PERSON_ID BIGINT NOT NULL,
  FODSELSNR VARCHAR(255) NOT NULL,
  ETTERNAVN VARCHAR(255),
  FORNAVN VARCHAR(255),
  NAV_KONTOR VARCHAR(255),
  FORMIDLINGSGRUPPEKODE VARCHAR(255),
  ISERV_FRA_DATO DATE,
  KVALIFISERINGSGRUPPEKODE VARCHAR(255),
  RETTIGHETSGRUPPEKODE VARCHAR(255),
  HOVEDMAALKODE VARCHAR(255),
  SIKKERHETSTILTAK_TYPE_KODE VARCHAR(255),
  FR_KODE VARCHAR(255),
  HAR_OPPFOLGINGSSAK VARCHAR(255),
  SPERRET_ANSATT VARCHAR(255),
  ER_DOED VARCHAR(255),
  DOED_FRA_DATO DATE,
  TIDSSTEMPEL DATE,
  PRIMARY KEY(PERSON_ID)
);

CREATE VIEW VW_OPPFOLGINGSBRUKER AS (
SELECT OB.*, 'ARENA-PERSON' AS KILDE 
FROM OPPFOLGINGSBRUKER OB
UNION
SELECT TOB.*, 'TEST-PERSON' AS KILDE 
FROM TEST_OPPFOLGINGSBRUKER TOB
WHERE TOB.PERSON_ID NOT IN (SELECT PERSON_ID FROM OPPFOLGINGSBRUKER));

-- TO REMOVE CHANGES:
--
-- DROP VIEW VW_OPPFOLGINGSBRUKER;
-- DROP TABLE TEST_OPPFOLGINGSBRUKER;

