create table METADATA
(
	SIST_INDEKSERT TIMESTAMP(6) not null,
	DIALOGAKTOR_SIST_OPPDATERT TIMESTAMP(6) default TO_TIMESTAMP('1970-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') not null,
	AKTIVITETER_SIST_OPPDATERT TIMESTAMP(6) default TO_TIMESTAMP('1970-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') not null,
	OPPFOLGING_SIST_OPPDATERT_ID NUMBER,
	SIST_INDEKSERT_ES TIMESTAMP(6) default TO_TIMESTAMP('1970-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') not null
)


create table AKTOERID_TO_PERSONID
(
	AKTOERID VARCHAR2(20) not null
		primary key,
	PERSONID VARCHAR2(29) not null,
	OPPRETTET_TIDSPUNKT TIMESTAMP(6) default CURRENT_TIMESTAMP,
	GJELDENE NUMBER(1)
)


create table BRUKER_DATA
(
	AKTOERID VARCHAR2(20),
	PERSONID VARCHAR2(20) not null
		primary key,
	YTELSE VARCHAR2(40),
	UTLOPSDATO TIMESTAMP(6),
	UTLOPSDATOFASETT VARCHAR2(10),
	DAGPUTLOPUKE NUMBER,
	DAGPUTLOPUKEFASETT VARCHAR2(20),
	PERMUTLOPUKE NUMBER,
	PERMUTLOPUKEFASETT VARCHAR2(20),
	AAPMAXTIDUKE NUMBER,
	AAPMAXTIDUKEFASETT VARCHAR2(20),
	NYESTEUTLOPTEAKTIVITET TIMESTAMP(6),
	FNR VARCHAR2(11),
	AAPUNNTAKDAGERIGJEN NUMBER,
	AAPUNNTAKUKERIGJENFASETT VARCHAR2(20),
	AKTIVITET_START TIMESTAMP(6),
	NESTE_AKTIVITET_START TIMESTAMP(6),
	FORRIGE_AKTIVITET_START TIMESTAMP(6)
)


create table AKTIVITETER
(
	AKTIVITETID VARCHAR2(20) not null
		primary key,
	AKTOERID VARCHAR2(30) not null,
	AKTIVITETTYPE VARCHAR2(255) not null,
	AVTALT VARCHAR2(20) not null,
	FRADATO TIMESTAMP(6),
	TILDATO TIMESTAMP(6),
	OPPDATERTDATO TIMESTAMP(6) not null,
	STATUS VARCHAR2(255) not null
)

create table BRUKERSTATUS_AKTIVITETER
(
	PERSONID VARCHAR2(30) not null,
	AKTOERID VARCHAR2(30),
	AKTIVITETTYPE VARCHAR2(255) not null,
	STATUS VARCHAR2(255) not null,
	NESTE_UTLOPSDATO TIMESTAMP(6),
	NESTE_STARTDATO TIMESTAMP(6),
	primary key (PERSONID, AKTIVITETTYPE)
)

create table ARBEIDSLISTE
(
	AKTOERID VARCHAR2(20) not null
		primary key,
	SIST_ENDRET_AV_VEILEDERIDENT VARCHAR2(20),
	KOMMENTAR VARCHAR2(1000),
	FRIST TIMESTAMP(6),
	ENDRINGSTIDSPUNKT TIMESTAMP(6),
	OVERSKRIFT VARCHAR2(500),
	KATEGORI VARCHAR2(10)
)


create table TILTAKKODEVERK
(
	KODE VARCHAR2(20) not null
		primary key,
	VERDI VARCHAR2(255) not null
)

create table BRUKERTILTAK
(
	FODSELSNR VARCHAR2(20) not null,
	TILTAKSKODE VARCHAR2(20) not null
		references TILTAKKODEVERK,
	TILDATO TIMESTAMP(6)
)

create table ENHETTILTAK
(
	ENHETID VARCHAR2(20) not null,
	TILTAKSKODE VARCHAR2(20) not null
		references TILTAKKODEVERK
)

create table TMP_KVP
(
	AKTOERID VARCHAR2(20) not null
		primary key,
	FNR VARCHAR2(11),
	DATO_START DATE,
	DATO_SLUTT DATE
)

create table OPPFOLGING_DATA
(
	AKTOERID VARCHAR2(20) not null
		primary key,
	VEILEDERIDENT VARCHAR2(20),
	OPPDATERT_KILDESYSTEM TIMESTAMP(6),
	OPPDATERT_PORTEFOLJE TIMESTAMP(6),
	OPPFOLGING VARCHAR2(1),
	NY_FOR_VEILEDER VARCHAR2(1),
	MANUELL VARCHAR2(1),
	FEED_ID NUMBER,
	STARTDATO TIMESTAMP(6)
)

create table DIALOG
(
	AKTOERID VARCHAR2(20) not null
		primary key,
	VENTER_PA_NAV TIMESTAMP(6),
	VENTER_PA_BRUKER TIMESTAMP(6),
	OPPDATERT_KILDESYSTEM TIMESTAMP(6),
	OPPDATERT_PORTEFOLJE TIMESTAMP(6)
)


create table KRR
(
	FODSELSNR VARCHAR2(11) not null
		constraint KRR_FODSELSNR_PK
			primary key,
	RESERVASJON VARCHAR2(1),
	SISTEVERIFISERT TIMESTAMP(6),
	LAGTTILIDB TIMESTAMP(6)
)


create table BRUKER_REGISTRERING
(
	AKTOERID VARCHAR2(20) not null
		primary key,
	BRUKERS_SITUASJON VARCHAR2(40),
	REGISTRERING_OPPRETTET TIMESTAMP(6),
	KAFKA_MELDING_MOTTATT TIMESTAMP(6)
)


create table VEDTAKSTATUS_DATA
(
	VEDTAKID VARCHAR2(20) not null
		primary key,
	AKTOERID VARCHAR2(20) not null,
	VEDTAKSTATUS VARCHAR2(40) not null,
	INNSATSGRUPPE VARCHAR2(40),
	HOVEDMAL VARCHAR2(30),
	VEDTAK_STATUS_ENDRET_TIDSPUNKT TIMESTAMP(6)
)


create table BRUKER_PROFILERING
(
	AKTOERID VARCHAR2(20) not null
		primary key,
	PROFILERING_RESULTAT VARCHAR2(40),
	PROFILERING_TIDSPUNKT TIMESTAMP(6)
)


create table BRUKER_CV
(
	AKTOERID VARCHAR2(20) not null
		primary key,
	FNR VARCHAR2(11),
	HAR_DELT_CV VARCHAR2(1),
	SISTE_MELDING_MOTTATT TIMESTAMP(6)
)

CREATE TABLE OPPFOLGINGSBRUKER (
  PERSON_ID NUMBER NOT NULL,
  FODSELSNR VARCHAR(255) NOT NULL,
  ETTERNAVN VARCHAR(255),
  FORNAVN VARCHAR(255),
  NAV_KONTOR VARCHAR(255),
  FORMIDLINGSGRUPPEKODE VARCHAR(255),
  ISERV_FRA_DATO DATE,
  KVALIFISERINGSGRUPPEKODE VARCHAR(255),
  RETTIGHETSGRUPPEKODE VARCHAR(255),
  HOVEDMAALKODE VARCHAR(255),
  SIKKERHETSTILTAK_TYPE_KODE VARCHAR(255),
  FR_KODE VARCHAR(255),
  HAR_OPPFOLGINGSSAK VARCHAR(255),
  SPERRET_ANSATT VARCHAR(255),
  ER_DOED VARCHAR(255),
  DOED_FRA_DATO DATE,
  TIDSSTEMPEL DATE,
  PRIMARY KEY(PERSON_ID)
);

