INSERT INTO DIALOG(
  AKTOERID,
  VENTER_PA_NAV, 
  VENTER_PA_BRUKER,
  OPPDATERT_KILDESYSTEM,
  OPPDATERT_PORTEFOLJE) 
SELECT 
  BD.AKTOERID AS AKTOERID,
  BD.VENTERPASVARFRANAV AS VENTER_PA_NAV, 
  BD.VENTERPASVARFRABRUKER AS VENTER_PA_BRUKER,
  NULL AS OPPDATERT_KILDESYSTEM,
  NULL AS OPPDATERT_PORTEFOLJE 
FROM BRUKER_DATA BD
WHERE BD.AKTOERID IS NOT NULL 
  AND BD.AKTOERID NOT IN (SELECT AKTOERID FROM DIALOG)
  AND (BD.VENTERPASVARFRANAV is not null OR BD.VENTERPASVARFRABRUKER is not null);