ALTER TABLE BRUKER_DATA ADD DAGPUTLOPUKE INTEGER;
ALTER TABLE BRUKER_DATA ADD DAGPUTLOPUKEFASETT VARCHAR(20);
ALTER TABLE BRUKER_DATA ADD PERMUTLOPUKE INTEGER;
ALTER TABLE BRUKER_DATA ADD PERMUTLOPUKEFASETT VARCHAR(20);
ALTER TABLE BRUKER_DATA ADD AAPMAXTIDUKE INTEGER;
ALTER TABLE BRUKER_DATA ADD AAPMAXTIDUKEFASETT VARCHAR(20);

ALTER TABLE BRUKER_DATA DROP COLUMN AAPMAXTID;
ALTER TABLE BRUKER_DATA DROP COLUMN AAPMAXTIDFASETT;