CREATE TABLE BRUKERTILTAK_V2
(
    AKTIVITETID VARCHAR(25) NOT NULL,
    AKTOERID    VARCHAR(20),
    PERSONID    VARCHAR(20),
    TILTAKSKODE VARCHAR(10),
    TILDATO     TIMESTAMP,

    PRIMARY KEY (AKTIVITETID)
);

CREATE INDEX PERSONID_IDX ON BRUKERTILTAK_V2 (PERSONID);