CREATE TABLE GRUPPE_AKTIVITER
(
    MOTEPLAN_ID           INTEGER NOT NULL,
    VEILEDNINGDELTAKER_ID INTEGER NOT NULL,

    AKTOERID              VARCHAR(20),
    MOTEPLAN_STARTDATO    TIMESTAMP,
    MOTEPLAN_SLUTTDATO    TIMESTAMP,
    HENDELSE_ID           INT,
    AKTIV                 VARCHAR(1) DEFAULT 'N',
    PRIMARY KEY (MOTEPLAN_ID, VEILEDNINGDELTAKER_ID)
);