CREATE TABLE BRUKERTILTAK_V2
(
    AKTIVITETID VARCHAR(25) NOT NULL,
    AKTOERID    VARCHAR(20),
    PERSONID    VARCHAR(20),
    TILTAKSKODE VARCHAR(10),
    TILDATO     TIMESTAMP,

    PRIMARY KEY (AKTIVITETID)
);

CREATE TABLE TILTAKKODEVERKET_V2
(
    KODE  VARCHAR(10),
    VERDI VARCHAR(80),

    PRIMARY KEY (KODE)
);

CREATE INDEX PERSONID_BRUKERTILTAK_IDX ON BRUKERTILTAK_V2 (PERSONID);
CREATE INDEX TILTAKKODEVERKET_V2_IDX ON TILTAKKODEVERKET_V2 (KODE);