ALTER TABLE YTELSER
    DROP COLUMN ANTALLUKERIGJEN;

ALTER TABLE YTELSER
    DROP COLUMN ANTALLPERMITTERINGUKER;

ALTER TABLE YTELSER
    DROP COLUMN ANTALLUKERIGJENUNNTAK;

ALTER TABLE YTELSER
    ADD ANTALLUKERIGJEN NUMBER(10);
ALTER TABLE YTELSER
    ADD ANTALLPERMITTERINGUKER NUMBER(10);
ALTER TABLE YTELSER
    ADD ANTALLUKERIGJENUNNTAK NUMBER(10);
