INSERT INTO OPPFOLGINGSBRUKER (PERSON_ID,FODSELSNR, ETTERNAVN, FORNAVN, FORMIDLINGSGRUPPEKODE, KVALIFISERINGSGRUPPEKODE, RETTIGHETSGRUPPEKODE, SPERRET_ANSATT, ER_DOED)
VALUES (1234567890,'01010101010', 'TESTESEN', 'TEST', 'ARBS', 'VARIG', 'IYT', 'N', 'N');

INSERT INTO OPPFOLGINGSBRUKER (PERSON_ID,FODSELSNR, ETTERNAVN, FORNAVN, NAV_KONTOR, FORMIDLINGSGRUPPEKODE, KVALIFISERINGSGRUPPEKODE, RETTIGHETSGRUPPEKODE, SPERRET_ANSATT, ER_DOED)
VALUES (9999,'99999999999', 'NIERSEN', 'NIER', '9999', 'ARBS', 'VARIG', 'IYT', 'N', 'N');


INSERT INTO METADATA (SIST_INDEKSERT)
VALUES (TIMESTAMP('1970-01-01 00:00:00.000000'));