package no.nav.pto.veilarbportefolje.tiltakshendelse.domain;

public enum Tiltakstype {
    //Gamle tiltakskoder som skal fases ut
    ARBFORB,
    ARBRRHDAG,
    AVKLARAG,
    DIGIOPPARB,
    INDOPPFAG,
    GRUFAGYRKE,
    GRUPPEAMO,
    JOBBK,
    VASV,

    //Nye tiltakskoder
    ARBEIDSFORBEREDENDE_TRENING,
    ARBEIDSRETTET_REHABILITERING,
    AVKLARING,
    DIGITALT_OPPFOLGINGSTILTAK,
    GRUPPE_ARBEIDSMARKEDSOPPLAERING,
    GRUPPE_FAG_OG_YRKESOPPLAERING,
    JOBBKLUBB,
    OPPFOLGING,
    VARIG_TILRETTELAGT_ARBEID_SKJERMET,
    HOYERE_UTDANNING,
    ENKELTPLASS_ARBEIDSMARKEDSOPPLAERING,
    ENKELTPLASS_FAG_OG_YRKESOPPLAERING,
    ARBEIDSMARKEDSOPPLAERING,
    NORSKOPPLAERING_GRUNNLEGGENDE_FERDIGHETER_FOV,
    STUDIESPESIALISERING,
    FAG_OG_YRKESOPPLAERING,
    HOYERE_YRKESFAGLIG_UTDANNING,
}
