# ref https://raw.githubusercontent.com/nais/naiserator/master/examples/nais-max.yaml
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbportefolje
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbportefolje/veilarbportefolje:{{version}}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  port: 8080
  ingresses:
    - https://veilarbportefolje-q1.nais.preprod.local
    - https://app-q1.adeo.no/veilarbportefolje
    - https://app-q1.dev.adeo.no/veilarbportefolje
    - https://veilarbportefolje-q1.dev.adeo.no
  webproxy: true
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvveilarbportefolje
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /oracle/data/dev/creds/veilarbportefolje_q1-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /kv/preprod/fss/veilarbportefolje/q1
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /oracle/data/dev/config/veilarbportefolje_q1
        mountPath: /var/run/secrets/nais.io/oracle_config
  envFrom:
    - configmap: pto-config
  leaderElection: true
  liveness:
    path: veilarbportefolje/internal/isAlive
    initialDelay: 60
    timeout: 10
  readiness:
    path: veilarbportefolje/internal/isReady
    initialDelay: 60
    timeout: 10
  prometheus:
    enabled: true
    path: veilarbportefolje/internal/prometheus
  resources:
    limits:
      cpu: "4"
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 4Gi
  env:
    - name: JAVA_OPTS
      value: "-Xms4098m -Xmx8096m --illegal-access=permit --add-opens=java.base/java.lang=ALL-UNNAMED"
    - name: ABAC_MODIA_URL
      value: https://abac-modia-q1.dev.intern.nav.no/application/asm-pdp/authorize
