# ref https://raw.githubusercontent.com/nais/naiserator/master/examples/nais-max.yaml
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbportefolje
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbportefolje/veilarbportefolje:{{version}}
  replicas:
    min: 3
    max: 3
    cpuThresholdPercentage: 50
  port: 8080
  ingresses:
    - https://veilarbportefolje.intern.nav.no
    - https://veilarbportefolje.prod-fss-pub.nais.io
    - https://veilarbportefolje.nais.adeo.no
    - https://app.adeo.no/veilarbportefolje
  webproxy: true
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvveilarbportefolje
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/prod/fss/veilarbportefolje/default
        mountPath: /var/run/secrets/nais.io/vault
  envFrom:
    - configmap: pto-config
  liveness:
    path: veilarbportefolje/internal/isAlive
    initialDelay: 60
    timeout: 10
  readiness:
    path: veilarbportefolje/internal/isReady
    initialDelay: 60
    timeout: 10
  prometheus:
    enabled: true
    path: veilarbportefolje/internal/prometheus
  openSearch:
    access: admin
    instance: veilarbportefolje
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident
          - azp_name
  accessPolicy:
    inbound:
      rules:
        - application: veilarbportefoljeflatefs
          namespace: obo
          cluster: prod-gcp
        - application: veilarbpersonflate
          namespace: poao
          cluster: prod-gcp
        - application: pto-admin
          namespace: pto
          cluster: prod-fss
  resources:
    limits:
      cpu: "4"
      memory: 10Gi
    requests:
      cpu: "1"
      memory: 4Gi
  env:
    - name: JAVA_OPTS
      value: "-Xms4096m -Xmx10144m --illegal-access=permit --add-opens=java.base/java.lang=ALL-UNNAMED"
