CREATE TABLE BRUKER_DATA (
  AKTOERID VARCHAR(20),
  VEILEDERIDENT VARCHAR(20),
  TILDELT_TIDSPUNKT TIMESTAMP,
  PERSONID VARCHAR(20),
  YTELSE VARCHAR(40),
  UTLOPSDATO TIMESTAMP,
  UTLOPSDATOFASETT VARCHAR(10),
  AAPMAXTID TIMESTAMP,
  AAPMAXTIDFASETT VARCHAR(10),
  OPPFOLGING VARCHAR2(1) NOT NULL,
  VENTERPASVARFRABRUKER TIMESTAMP,
  VENTERPASVARFRANAV TIMESTAMP,
  PRIMARY KEY (PERSONID));