CREATE TABLE BRUKERSTATUS_AKTIVITETER (
  PERSONID VARCHAR(30) NOT NULL,
  AKTOERID VARCHAR(30) NOT NULL,
  AKTIVITETTYPE VARCHAR(255) NOT NULL,
  STATUS VARCHAR(255) NOT NULL,
  PRIMARY KEY (PERSONID, AKTOERID)
);
