CREATE TABLE SIKKERHETSTILTAK_TYPE_KODE
(
  SIKKERHETSTILTAK_TYPE_KODE VARCHAR2(4) PRIMARY KEY,
  SIKKERHETSTILTAK_BESKRIVELSE VARCHAR2(100) NOT NULL
);

INSERT INTO SIKKERHETSTILTAK_TYPE_KODE (SIKKERHETSTILTAK_TYPE_KODE, SIKKERHETSTILTAK_BESKRIVELSE) VALUES ('FTUS', 'Fysisk/telefonisk utestengelse');
INSERT INTO SIKKERHETSTILTAK_TYPE_KODE (SIKKERHETSTILTAK_TYPE_KODE, SIKKERHETSTILTAK_BESKRIVELSE) VALUES ('FYUS', 'Fysisk utestengelse');
INSERT INTO SIKKERHETSTILTAK_TYPE_KODE (SIKKERHETSTILTAK_TYPE_KODE, SIKKERHETSTILTAK_BESKRIVELSE) VALUES ('TOAN', 'To ansatte i samtale');

ALTER TABLE T4_VEILARBPORTEFOLJE.OPPFOLGINGSBRUKER
  ADD CONSTRAINT SIKKERHETSTILTAK_TYPE_KODE__fk
FOREIGN KEY (SIKKERHETSTILTAK_TYPE_KODE) REFERENCES SIKKERHETSTILTAK_TYPE_KODE (SIKKERHETSTILTAK_TYPE_KODE)