INSERT INTO TILTAKKODEVERK (KODE, VERDI) VALUES ('A', 'Tiltak1');
INSERT INTO TILTAKKODEVERK (KODE, VERDI) VALUES ('B', 'Tiltak2');

INSERT INTO BRUKERTILTAK (PERSONID, TILTAKSKODE) VALUES (2343601, 'A');
INSERT INTO BRUKERTILTAK (PERSONID, TILTAKSKODE) VALUES (2343601, 'B');
INSERT INTO BRUKERTILTAK (PERSONID, TILTAKSKODE) VALUES (2343602, 'B');