INSERT INTO TILTAKKODEVERK (KODE, VERDI) VALUES ('T1', 'Tiltak1');
INSERT INTO TILTAKKODEVERK (KODE, VERDI) VALUES ('T2', 'Tiltak2');

INSERT INTO BRUKERTILTAK (PERSONID, TILTAKSKODE) VALUES (11111111111, 'T1');
INSERT INTO BRUKERTILTAK (PERSONID, TILTAKSKODE) VALUES (22222222222, 'T2');
INSERT INTO BRUKERTILTAK (PERSONID, TILTAKSKODE) VALUES (22222222222, 'T1');

INSERT INTO ENHETTILTAK (ENHETID, TILTAKSKODE) VALUES (1234, 'T1');
INSERT INTO ENHETTILTAK (ENHETID, TILTAKSKODE) VALUES (1234, 'T2');
INSERT INTO ENHETTILTAK (ENHETID, TILTAKSKODE) VALUES (5678, 'T2');