DEFINE arenaLink = 'arena';

CREATE TABLE METADATA
(
  SIST_INDEKSERT   TIMESTAMP    NOT NULL
);

INSERT INTO METADATA (SIST_INDEKSERT)
VALUES (TO_TIMESTAMP('1970-01-01 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'));

CREATE MATERIALIZED VIEW OPPFOLGINGSBRUKER
BUILD IMMEDIATE
REFRESH FAST
ON DEMAND NEXT sysdate + 60 / 86400
AS
  SELECT *
  FROM OPPFOLGINGSBRUKER@&arenaLink;


CREATE MATERIALIZED VIEW SIKKERHETSTILTAK_TYPE
BUILD IMMEDIATE
REFRESH FAST
ON DEMAND NEXT sysdate + 60 / 86400
AS
  SELECT *
  FROM SIKKERHETSTILTAK_TYPE@&arenaLink;


CREATE MATERIALIZED VIEW HOVEDMAAL
BUILD IMMEDIATE
REFRESH FAST
ON DEMAND NEXT sysdate + 60 / 86400
AS
  SELECT *
  FROM HOVEDMAAL@&arenaLink;

CREATE MATERIALIZED VIEW RETTIGHETSGRUPPETYPE
BUILD IMMEDIATE
REFRESH FAST
ON DEMAND NEXT sysdate + 60 / 86400
AS
  SELECT *
  FROM RETTIGHETSGRUPPETYPE@&arenaLink;


CREATE MATERIALIZED VIEW KVALIFISERINGSGRUPPETYPE
BUILD IMMEDIATE
REFRESH FAST
ON DEMAND NEXT sysdate + 60 / 86400
AS
  SELECT *
  FROM KVALIFISERINGSGRUPPETYPE@&arenaLink;

CREATE MATERIALIZED VIEW FORMIDLINGSGRUPPETYPE
BUILD IMMEDIATE
REFRESH FAST
ON DEMAND NEXT sysdate + 60 / 86400
AS
  SELECT *
  FROM FORMIDLINGSGRUPPETYPE@&arenaLink;