query($ident: ID!) {
  hentPerson(ident: $ident) {
    bostedsadresse {
      vegadresse {
        matrikkelId
        husbokstav
        husnummer
        adressenavn
        bruksenhetsnummer
        tilleggsnavn
        postnummer
        kommunenummer
        bydelsnummer
      }
      matrikkeladresse {
        matrikkelId
        bruksenhetsnummer
        tilleggsnavn
        postnummer
        kommunenummer
      }
      utenlandskAdresse {
        adressenavnNummer
        bygningEtasjeLeilighet
        postboksNummerNavn
        postkode
        bySted
        regionDistriktOmraade
        landkode
      }
      ukjentBosted {
        bostedskommune
      }

      metadata {
        ...metadataDetails
      }
    }
    adressebeskyttelse {
      gradering

      metadata {
        ...metadataDetails
      }
    }
    doedsfall {
        doedsdato
    }
}

fragment metadataDetails on Metadata {
  master
  historisk
  endringer {
    registrert
  }
}
