query($ident: ID!) {
  hentPerson(ident: $ident) {
    navn {
      fornavn
      mellomnavn
      etternavn
      metadata {
        ...metadataDetails
      }
    }
    foedsel {
      foedselsdato
      foedeland
      metadata {
        ...metadataDetails
      }
    }
    kjoenn {
      kjoenn
      metadata {
        ...metadataDetails
      }
    }
    doedsfall {
      doedsdato
    }
    statsborgerskap {
      land
      gyldigFraOgMed
      gyldigTilOgMed
      metadata {
        ...metadataDetails
      }
    }
    bostedsadresse {
      vegadresse {
        matrikkelId
        husbokstav
        husnummer
        adressenavn
        bruksenhetsnummer
        tilleggsnavn
        postnummer
        kommunenummer
        bydelsnummer
      }
      matrikkeladresse {
        matrikkelId
        bruksenhetsnummer
        tilleggsnavn
        postnummer
        kommunenummer
      }
      utenlandskAdresse {
        adressenavnNummer
        bygningEtasjeLeilighet
        postboksNummerNavn
        postkode
        bySted
        regionDistriktOmraade
        landkode
      }
      ukjentBosted {
        bostedskommune
      }

      metadata {
        ...metadataDetails
      }
    }
    adressebeskyttelseDto {
      gradering

      metadata {
        ...metadataDetails
      }
    }
    sikkerhetstiltak {
      tiltakstype
      beskrivelse
      gyldigFraOgMed
      gyldigTilOgMed
      metadata {
        ...metadataDetails
      }
    }
    tilrettelagtKommunikasjon {
      talespraaktolk {
        spraak
      }
      tegnspraaktolk {
        spraak
      }
      metadata {
        ...metadataDetails
      }
    }
  }
}

fragment metadataDetails on Metadata {
  master
  historisk
  endringer {
    registrert
  }
}
