query($ident: ID! ) {
  hentPerson(ident: $ident) {
    navn {
      fornavn
      mellomnavn
      etternavn
      metadata {
        ...metadataDetails
      }
    }
    foedsel {
      foedselsdato
      foedeland
      metadata {
        ...metadataDetails
      }
    }
    kjoenn {
      kjoenn
      metadata {
        ...metadataDetails
      }
    }
    doedsfall {
      doedsdato
    }
    statsborgerskap {
      land
      gyldigFraOgMed
      gyldigTilOgMed
      metadata {
        ...metadataDetails
      }
    }
    bostedsadresse {
      vegadresse {
        kommunenummer
        bydelsnummer
      }
      utenlandskAdresse {
        landkode
      }
      ukjentBosted {
        bostedskommune
      }

      metadata {
        ...metadataDetails
      }
    }
    tilrettelagtKommunikasjon {
      talespraaktolk {
        spraak
      }
      tegnspraaktolk {
        spraak
      }
      metadata {
        ...metadataDetails
      }
    }
  }
}

fragment metadataDetails on Metadata {
  master
  historisk
  endringer {
    registrert
  }
}
