package no.nav.pto.veilarbportefolje.opensearch.domene;

import lombok.Data;
import lombok.experimental.Accessors;
import no.nav.pto.veilarbportefolje.aap.domene.AapRettighetstype;
import no.nav.pto.veilarbportefolje.arbeidssoeker.v2.Profileringsresultat;
import no.nav.pto.veilarbportefolje.domene.EnsligeForsorgereOvergangsstonad;
import no.nav.pto.veilarbportefolje.domene.HuskelappForBruker;
import no.nav.pto.veilarbportefolje.domene.Statsborgerskap;
import no.nav.pto.veilarbportefolje.hendelsesfilter.Hendelse;
import no.nav.pto.veilarbportefolje.oppfolgingsvedtak14a.avvik14aVedtak.Avvik14aVedtak;
import no.nav.pto.veilarbportefolje.oppfolgingsvedtak14a.gjeldende14aVedtak.GjeldendeVedtak14a;
import no.nav.pto.veilarbportefolje.persononinfo.barnUnder18Aar.BarnUnder18AarData;
import no.nav.pto.veilarbportefolje.tiltakshendelse.domain.Tiltakshendelse;
import no.nav.pto.veilarbportefolje.tiltakspenger.domene.TiltakspengerRettighet;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.Set;

import static java.util.Collections.emptyList;
import static java.util.Collections.emptySet;
import static no.nav.pto.veilarbportefolje.util.DateUtils.getFarInTheFutureDate;

@Data
@Accessors(chain = true)
public class PortefoljebrukerOpensearchModell {
    public String fnr;
    public String aktoer_id;
    public String fornavn;
    public String etternavn;
    public String fullt_navn;
    public String enhet_id;
    public String formidlingsgruppekode;
    public String iserv_fra_dato;
    public String kvalifiseringsgruppekode;
    public String rettighetsgruppekode;
    public String sikkerhetstiltak;
    public String sikkerhetstiltak_gyldig_fra;
    public String sikkerhetstiltak_gyldig_til;
    public String sikkerhetstiltak_beskrivelse;
    public String diskresjonskode;
    public boolean har_delt_cv;
    public boolean cv_eksistere;
    public boolean egen_ansatt;
    public LocalDateTime skjermet_til;
    public boolean er_doed;
    public String veileder_id;
    public int fodselsdag_i_mnd;
    public String fodselsdato;
    public String foedeland;
    public String foedelandFulltNavn;
    public String kjonn;
    public String ytelse;
    public String utlopsdato;
    public Integer dagputlopuke;
    public Integer permutlopuke;
    public Integer aapmaxtiduke;
    public Integer aapunntakukerigjen;
    public LocalDate aapordinerutlopsdato;
    public boolean aap_kelvin;
    public LocalDate aap_kelvin_tom_vedtaksdato;
    public AapRettighetstype aap_kelvin_rettighetstype;
    public boolean tiltakspenger;
    public LocalDate tiltakspenger_vedtaksdato_tom;
    public TiltakspengerRettighet tiltakspenger_rettighet;
    public boolean oppfolging;
    public boolean ny_for_veileder;
    public LocalDateTime tildelt_tidspunkt;
    public boolean trenger_vurdering;
    public String venterpasvarfrabruker;
    public String venterpasvarfranav;
    public String nyesteutlopteaktivitet;
    public String aktivitet_start;
    public String neste_aktivitet_start;
    public String forrige_aktivitet_start;
    public String manuell_bruker;
    public String aktivitet_mote_startdato = getFarInTheFutureDate();
    public String aktivitet_mote_utlopsdato = getFarInTheFutureDate();
    public String aktivitet_stilling_utlopsdato = getFarInTheFutureDate();
    public String aktivitet_egen_utlopsdato = getFarInTheFutureDate();
    public String aktivitet_behandling_utlopsdato = getFarInTheFutureDate();
    public String aktivitet_ijobb_utlopsdato = getFarInTheFutureDate();
    public String aktivitet_sokeavtale_utlopsdato = getFarInTheFutureDate();
    public String aktivitet_tiltak_utlopsdato = getFarInTheFutureDate();
    public String aktivitet_utdanningaktivitet_utlopsdato = getFarInTheFutureDate();
    public String aktivitet_gruppeaktivitet_utlopsdato = getFarInTheFutureDate();
    public String alle_aktiviteter_mote_startdato = getFarInTheFutureDate();
    public String alle_aktiviteter_mote_utlopsdato = getFarInTheFutureDate();
    public String alle_aktiviteter_stilling_utlopsdato = getFarInTheFutureDate();
    public String alle_aktiviteter_egen_utlopsdato = getFarInTheFutureDate();
    public String alle_aktiviteter_behandling_utlopsdato = getFarInTheFutureDate();
    public String alle_aktiviteter_ijobb_utlopsdato = getFarInTheFutureDate();
    public String alle_aktiviteter_sokeavtale_utlopsdato = getFarInTheFutureDate();
    public String oppfolging_startdato;
    public Set<String> alleAktiviteter = emptySet();
    public Set<String> aktiviteter = emptySet();
    public Set<String> tiltak = emptySet();
    public String utkast_14a_status;
    public String utkast_14a_status_endret;
    public String utkast_14a_ansvarlig_veileder;
    public boolean er_sykmeldt_med_arbeidsgiver;
    public List<String> brukers_situasjoner;
    public LocalDate brukers_situasjon_sist_endret;
    public LocalDate utdanning_og_situasjon_sist_endret;
    public Profileringsresultat profilering_resultat;
    public String utdanning;
    public String utdanning_bestatt;
    public String utdanning_godkjent;
    public Map<String, Endring> siste_endringer;
    public String talespraaktolk;
    public String tegnspraaktolk;
    public LocalDate tolkBehovSistOppdatert;
    public String landgruppe;
    public boolean harFlereStatsborgerskap;
    public Statsborgerskap hovedStatsborgerskap;
    public String kommunenummer;
    public String bydelsnummer;
    public String utenlandskAdresse;
    public boolean harUkjentBosted;
    public LocalDate bostedSistOppdatert;
    public String neste_cv_kan_deles_status;
    public LocalDate neste_svarfrist_stilling_fra_nav;
    public Avvik14aVedtak avvik14aVedtak;
    public List<BarnUnder18AarData> barn_under_18_aar = emptyList();

    public EnsligeForsorgereOvergangsstonad enslige_forsorgere_overgangsstonad;
    public HuskelappForBruker huskelapp;
    public String fargekategori;
    public String fargekategori_enhetId;
    public Tiltakshendelse tiltakshendelse;

    public GjeldendeVedtak14a gjeldendeVedtak14a;
    public Hendelse.HendelseInnhold utgatt_varsel;
}
