package no.nav.pto.veilarbportefolje.domene.filtervalg;

public enum DinSituasjonSvar {
    MISTET_JOBBEN,
    ALDRI_HATT_JOBB,
    HAR_SAGT_OPP,
    VIL_BYTTE_JOBB,
    ER_PERMITTERT,
    USIKKER_JOBBSITUASJON,
    JOBB_OVER_2_AAR,
    VIL_FORTSETTE_I_JOBB,
    AKKURAT_FULLFORT_UTDANNING,
    DELTIDSJOBB_VIL_MER,
    OPPSIGELSE,
    ENDRET_PERMITTERINGSPROSENT,
    TILBAKE_TIL_JOBB,
    NY_JOBB,
    MIDLERTIDIG_JOBB,
    KONKURS,
    SAGT_OPP,
    ANNET,
    INGEN_DATA

}
