CREATE OR REPLACE PROCEDURE REFRESH_MV AS
  BEGIN
    DBMS_MVIEW.REFRESH('OPPFOLGINGSBRUKER','F');
    DBMS_MVIEW.REFRESH('SIKKERHETSTILTAK_TYPE','F');
    DBMS_MVIEW.REFRESH('HOVEDMAAL','F');
    DBMS_MVIEW.REFRESH('RETTIGHETSGRUPPETYPE','F');
    DBMS_MVIEW.REFRESH('KVALIFISERINGSGRUPPETYPE','F');
    DBMS_MVIEW.REFRESH('FORMIDLINGSGRUPPETYPE','F');
  END REFRESH_MV;

CREATE OR REPLACE TRIGGER restartmateralizedviews AFTER STARTUP ON DATABASE
  Begin
    REFRESH_MV();
  End;
