DROP MATERIALIZED VIEW OPPFOLGINGSBRUKER;
DROP MATERIALIZED VIEW SIKKERHETSTILTAK_TYPE;
DROP MATERIALIZED VIEW RETTIGHETSGRUPPETYPE;
DROP MATERIALIZED VIEW KVALIFISERINGSGRUPPETYPE;
DROP MATERIALIZED VIEW FORMIDLINGSGRUPPETYPE;

CREATE MATERIALIZED VIEW OPPFOLGINGSBRUKER
BUILD IMMEDIATE
REFRESH FAST
ON COMMIT
AS
  SELECT *
  FROM OPPFOLGINGSBRUKER@arena;


CREATE MATERIALIZED VIEW SIKKERHETSTILTAK_TYPE
BUILD IMMEDIATE
REFRESH FAST
ON COMMIT
AS
  SELECT *
  FROM SIKKERHETSTILTAK_TYPE@arena;


CREATE MATERIALIZED VIEW HOVEDMAAL
BUILD IMMEDIATE
REFRESH FAST
ON COMMIT
AS
  SELECT *
  FROM HOVEDMAAL@arena;

CREATE MATERIALIZED VIEW RETTIGHETSGRUPPETYPE
BUILD IMMEDIATE
REFRESH FAST
ON COMMIT
AS
  SELECT *
  FROM RETTIGHETSGRUPPETYPE@arena;


CREATE MATERIALIZED VIEW KVALIFISERINGSGRUPPETYPE
BUILD IMMEDIATE
REFRESH FAST
ON COMMIT
AS
  SELECT *
  FROM KVALIFISERINGSGRUPPETYPE@arena;

CREATE MATERIALIZED VIEW FORMIDLINGSGRUPPETYPE
BUILD IMMEDIATE
REFRESH FAST
ON COMMIT
AS
  SELECT *
  FROM FORMIDLINGSGRUPPETYPE@arena;