CREATE TABLE ARBEIDSLISTE (
  AKTOERID          VARCHAR2(20) NOT NULL,
  VEILEDERIDENT     VARCHAR2(20),
  ENDRINGSTIDSPUNKT TIMESTAMP,
  BESKRIVELSE       VARCHAR2(1000),
  FRIST             TIMESTAMP,
  PRIMARY KEY (AKTOERID)
);