CREATE TABLE OPPFOLGING_DATA (
  AKTOERID VARCHAR(20) NOT NULL,
  VEILEDERIDENT VARCHAR(20),
  OPPDATERT_KILDESYSTEM TIMESTAMP,
  OPPDATERT_PORTEFOLJE TIMESTAMP,
  OPPFOLGING VARCHAR2(1),  
  NY_FOR_VEILEDER VARCHAR2(1),  
  PRIMARY KEY (AKTOERID)
);

CREATE INDEX OPPFOLGING_DATA_AKTOR_IDX ON OPPFOLGING_DATA(AKTOERID);

-- To remove changes:
--
-- DROP INDEX OPPFOLGING_DATA_AKTOR_IDX;
-- DROP TABLE OPPFOLGING_DATA;
