ALTER TABLE BRUKER_DATA
  ADD (
  AKTIVITET_START TIMESTAMP,
  NESTE_AKTIVITET_START TIMESTAMP,
  FORRIGE_AKTIVITET_START TIMESTAMP
);

-- To remove changes:
--
-- ALTER TABLE BRUKER_DATA
-- DROP (AKTIVITET_START, NESTE_AKTIVITET_START, FORRIGE_AKTIVITET_START);
