CREATE VIEW VW_AKTOERID_TO_PERSONID AS (
SELECT AKTOERID AS AKTOERID, PERSONID AS PERSONID FROM AKTOERID_TO_PERSONID
UNION
SELECT AKTOERID AS AKTOERID, PERSONID AS PERSONID  FROM BRUKER_DATA
WHERE AKTOERID IS NOT NULL 
  AND PERSONID IS NOT NULL 
  AND AKTOERID NOT IN (SELECT AKTOERID FROM AKTOERID_TO_PERSONID))

-- TO REMOVE CHANGES:
--
-- DROP VIEW VW_AKTOERID_TO_PERSONID;
