INSERT INTO OPPFOLGING_DATA(
  AKTOERID, 
  OPPDATERT_KILDESYSTEM, 
  OPPDATERT_PORTEFOLJE, 
  NY_FOR_VEILEDER, 
  VEILEDERIDENT, 
  OPPFOLGING) 
SELECT 
  BD.AKTOERID,
  BD.TILDELT_TIDSPUNKT, 
  NULL, 
  BD.NY_FOR_VEILEDER,
  BD.VEILEDERIDENT,
  BD.OPPFOLGING
FROM BRUKER_DATA BD
WHERE BD.AKTOERID IS NOT NULL
  AND BD.AKTOERID NOT IN (SELECT AKTOERID FROM OPPFOLGING_DATA);