ALTER TABLE BRUKER_DATA DROP COLUMN VEILEDERIDENT;
ALTER TABLE BRUKER_DATA DROP COLUMN TILDELT_TIDSPUNKT;
ALTER TABLE BRUKER_DATA DROP COLUMN OPPFOLGING;
ALTER TABLE BRUKER_DATA DROP COLUMN NY_FOR_VEILEDER;