DROP TABLE BRUKER_DATA;

CREATE TABLE BRUKER_DATA (
  AKTOERID VARCHAR(20),
  VEILEDERIDENT VARCHAR(20),
  TILDELT_TIDSPUNKT TIMESTAMP,
  PERSONID VARCHAR(20),
  YTELSE VARCHAR(40),
  UTLOPSDATO TIMESTAMP,
  UTLOPSDATOFASETT VARCHAR(10),
  DAGPUTLOPUKE INTEGER,
  DAGPUTLOPUKEFASETT VARCHAR(20),
  PERMUTLOPUKE INTEGER,
  PERMUTLOPUKEFASETT VARCHAR(20),
  AAPMAXTIDUKE INTEGER,
  AAPMAXTIDUKEFASETT VARCHAR(20),
  PRIMARY KEY (PERSONID));
