ALTER TABLE BRUKER_DATA
ADD (
  DAGPUTLOPUKE INTEGER,
  DAGPUTLOPUKEFASETT VARCHAR(20),
  PERMUTLOPUKE INTEGER,
  PERMUTLOPUKEFASETT VARCHAR(20),
  AAPMAXTIDUKE INTEGER,
  AAPMAXTIDUKEFASETT VARCHAR(20)
);
ALTER TABLE BRUKER_DATA
DROP (
  AAPMAXTID,
  AAPMAXTIDFASETT
);