DELETE FROM AKTOERID_TO_PERSONID a
WHERE a.ROWID > ANY (
  SELECT b.ROWID
  FROM AKTOERID_TO_PERSONID b
  WHERE a.PERSONID = b.PERSONID
        AND a.AKTOERID <> b.AKTOERID
);
CREATE UNIQUE INDEX AKTOERID_TO_PERSONID.PERSONID_uindex ON AKTOERID_TO_PERSONID(PERSONID);