CREATE SEQUENCE FEILET_KAFKA_MELDING_SEQ START WITH 1;
CREATE SEQUENCE KAFKA_CONSUMER_RECORD_ID_SEQ START WITH 1;

ALTER TABLE FEILET_KAFKA_MELDING
    ALTER COLUMN ID SET DEFAULT nextval(FEILET_KAFKA_MELDING_SEQ);
ALTER TABLE KAFKA_CONSUMER_RECORD
    ALTER COLUMN ID SET DEFAULT nextval(KAFKA_CONSUMER_RECORD_ID_SEQ);