CREATE TABLE OPPFOLGING_DATA
(
    AKTOERID        VARCHAR(20) NOT NULL,
    VEILEDERID      VARCHAR(20),
    OPPFOLGING      boolean DEFAULT false,
    NY_FOR_VEILEDER boolean DEFAULT false,
    MANUELL         boolean DEFAULT false,
    STARTDATO       TIMESTAMP,

    PRIMARY KEY (AKTOERID)
);

CREATE UNIQUE INDEX OPPFOLGING_DATA_IDX ON OPPFOLGING_DATA (VEILEDERID);

CREATE TABLE OPPFOLGINGSBRUKER_ARENA
(
    AKTOERID                   VARCHAR(20) NOT NULL,
    FODSELSNR                  VARCHAR(33),
    FORMIDLINGSGRUPPEKODE      VARCHAR(15),
    ISERV_FRA_DATO             TIMESTAMP,
    ETTERNAVN                  VARCHAR(90),
    FORNAVN                    VARCHAR(90),
    NAV_KONTOR                 varchar(24),
    KVALIFISERINGSGRUPPEKODE   varchar(15),
    RETTIGHETSGRUPPEKODE       varchar(15),
    HOVEDMAALKODE              varchar(30),
    SIKKERHETSTILTAK_TYPE_KODE varchar(12),
    DISKRESJONSKODE            varchar(6),
    HAR_OPPFOLGINGSSAK         boolean DEFAULT false,
    SPERRET_ANSATT             boolean DEFAULT false,
    ER_DOED                    boolean DEFAULT false,
    DOED_FRA_DATO              TIMESTAMP,
    ENDRET_DATO                TIMESTAMP,

    PRIMARY KEY (AKTOERID)
);

CREATE VIEW BRUKER AS
SELECT OD.AKTOERID, OD.OPPFOLGING, OD.NY_FOR_VEILEDER, OD.VEILEDERID, OBA.FODSELSNR, OBA.FORNAVN, OBA.ETTERNAVN, OBA.NAV_KONTOR, OBA.DISKRESJONSKODE
FROM OPPFOLGING_DATA OD
         LEFT JOIN OPPFOLGINGSBRUKER_ARENA OBA ON OBA.AKTOERID = OD.AKTOERID;
