CREATE TABLE ARBEIDSLISTE
(
    AKTOERID                     VARCHAR(20) NOT NULL,
    SIST_ENDRET_AV_VEILEDERIDENT TIMESTAMP,
    KOMMENTAR                    VARCHAR(1000),
    FRIST                        TIMESTAMP,
    ENDRINGSTIDSPUNKT            TIMESTAMP,
    OVERSKRIFT                   VARCHAR(500),
    KATEGORI                     VARCHAR(10),
    NAV_KONTOR_FOR_ARBEIDSLISTE  VARCHAR(24),

    PRIMARY KEY (AKTOERID)
);