DROP VIEW BRUKER;

CREATE VIEW ESSENSIELL_BRUKER AS
SELECT OD.AKTOERID, OD.OPPFOLGING,OD.STARTDATO, OD.NY_FOR_VEILEDER, OD.VEILEDERID, OBA.FODSELSNR, OBA.FORNAVN, OBA.ETTERNAVN, OBA.NAV_KONTOR, OBA.DISKRESJONSKODE
FROM OPPFOLGING_DATA OD
         LEFT JOIN OPPFOLGINGSBRUKER_ARENA OBA ON OBA.AKTOERID = OD.AKTOERID;


CREATE VIEW BRUKER AS
SELECT
       OD.AKTOERID, OD.OPPFOLGING, OD.STARTDATO, OD.NY_FOR_VEILEDER, OD.VEILEDERID,
       OD.MANUELL,

       OBA.FODSELSNR, OBA.FORNAVN, OBA.ETTERNAVN, OBA.NAV_KONTOR, OBA.ISERV_FRA_DATO,
       OBA.FORMIDLINGSGRUPPEKODE, OBA.KVALIFISERINGSGRUPPEKODE, OBA.RETTIGHETSGRUPPEKODE,
       OBA.HOVEDMAALKODE, OBA.SIKKERHETSTILTAK_TYPE_KODE, OBA.DISKRESJONSKODE,
       OBA.HAR_OPPFOLGINGSSAK, OBA.SPERRET_ANSATT, OBA.DOED_FRA_DATO,

       D.VENTER_PA_BRUKER, D.VENTER_PA_NAV

FROM OPPFOLGING_DATA OD
         LEFT JOIN OPPFOLGINGSBRUKER_ARENA OBA ON OBA.AKTOERID = OD.AKTOERID
         LEFT JOIN DIALOG D ON D.AKTOERID = OD.AKTOERID;