CREATE TABLE BRUKER_AKTIVITETER
(
    AKTIVITETID   VARCHAR(20),
    AKTOERID      VARCHAR(20) NOT NULL,
    AKTIVITETTYPE VARCHAR(25),
    STATUS        VARCHAR(25),
    ENDRINGSTYPE  VARCHAR(25),
    FRADATO       TIMESTAMP,
    TILDATO       TIMESTAMP,
    ENDRETDATO    TIMESTAMP,
    TILTAKSKODE   VARCHAR(100),
    LAGTINNAV     VARCHAR(25),
    AVTALT        boolean default true,
    VERSION       bigint,
    HISTORISK     boolean default false,
    CV_KAN_DELES_STATUS VARCHAR(20),
    SVARFRIST_STILLING_FRA_NAV TIMESTAMP
    PRIMARY KEY (AKTIVITETID)
);

CREATE INDEX AKTIVITET_PKEY_INDEX ON BRUKER_AKTIVITETER(AKTIVITETID);
CREATE INDEX AKTOER_AKTIVITET_INDEX ON BRUKER_AKTIVITETER(AKTOERID);