CREATE TABLE BRUKER_REGISTRERT_CV
(
    AKTOERID              VARCHAR(20) NOT NULL,
    CV_EKSISTERER         boolean DEFAULT false NOT NULL,
    SISTE_MELDING_MOTTATT TIMESTAMP,

    PRIMARY KEY (AKTOERID)
);