CREATE TABLE AKTIVITETER
(
    AKTIVITETID   VARCHAR(20),
    AKTOERID      VARCHAR(20) NOT NULL,
    AKTIVITETTYPE VARCHAR(255),
    AVTALT        boolean default true,
    FRADATO       TIMESTAMP,
    TILDATO       TIMESTAMP,
    STATUS        VARCHAR(255),
    VERSION       bigint,
    PRIMARY KEY (AKTIVITETID)
);

CREATE TABLE PROSSESERT_AKTIVIT_DATA
(
    AKTOERID         VARCHAR(20) NOT NULL,
    AKTIVITETTYPE    VARCHAR(255),
    NESTE_UTLOPSDATO TIMESTAMP,
    NESTE_STARTDATO  TIMESTAMP,
    AKTIV            boolean default false,
    PRIMARY KEY (AKTOERID, AKTIVITETTYPE)
);