CREATE TABLE TILTAKSAKTIVITET
(
    AKTIVITETID VARCHAR(25) NOT NULL,
    AKTOERID    VARCHAR(20),
    TILTAKSKODE VARCHAR(100),
    TILDATO     TIMESTAMP,
    FRADATO     TIMESTAMP,
    VERSION     BIGINT,
    STATUS      VARCHAR(255),

    PRIMARY KEY (AKTIVITETID)
);

CREATE INDEX TILTAKSAKTIVITET_AKTIVITETID_PK_INDEX ON TILTAKSAKTIVITET (AKTIVITETID);
CREATE INDEX TILTAKSAKTIVITET_AKTOERID_INDEX ON TILTAKSAKTIVITET (AKTOERID);
CREATE INDEX TILTAKSAKTIVITET_STATUS_INDEX on TILTAKSAKTIVITET (STATUS);