CREATE TABLE BRUKER_REGISTRERT_CV
(
    FNR                   VARCHAR(11) NOT NULL,
    CV_EKSISTERER         boolean DEFAULT false NOT NULL,
    CV_SIST_ENDRET        TIMESTAMP,
    SISTE_MELDING_MOTTATT TIMESTAMP,

    PRIMARY KEY (FNR)
);