ALTER TABLE KAFKA_AKTIVITET_MELDING
    ALTER COLUMN FRA_DATO TYPE TEXT,
    ALTER COLUMN TIL_DATO TYPE TEXT,
    ALTER COLUMN ENDRET_DATO TYPE TEXT,
    ALTER COLUMN HISTORISK DROP DEFAULT,
    ALTER COLUMN HISTORISK SET NOT NULL,
    ALTER COLUMN AVTALT DROP DEFAULT,
    ALTER COLUMN AVTALT SET NOT NULL,
    ALTER COLUMN SVARFRIST_STILLING_FRA_NAV TYPE TEXT,
    ALTER COLUMN RAD_OPPRETTET TYPE TIMESTAMPTZ,
    ALTER COLUMN RAD_OPPDATERT TYPE TIMESTAMPTZ