CREATE TABLE KAFKA_AKTIVITET_MELDING
(
    AKTIVITET_ID   VARCHAR(20) PRIMARY KEY,
    AKTOR_ID      VARCHAR(20) NOT NULL,
    AKTIVITET_TYPE VARCHAR(25),
    AKTIVITET_STATUS  VARCHAR(25),
    ENDRINGS_TYPE  VARCHAR(25),
    FRA_DATO       TIMESTAMP,
    TIL_DATO       TIMESTAMP,
    ENDRET_DATO    TIMESTAMP,
    TILTAKSKODE   VARCHAR(100),
    LAGT_INN_AV     VARCHAR(25),
    AVTALT        BOOLEAN DEFAULT TRUE,
    VERSION       INT NOT NULL,
    HISTORISK     BOOLEAN DEFAULT FALSE,
    CV_KAN_DELES_STATUS VARCHAR(20),
    SVARFRIST_STILLING_FRA_NAV TIMESTAMP,
    -- Metadata
    RECORD_OFFSET        INT NOT NULL,
    RECORD_PARTITION     INT NOT NULL,
    RECORD_KEY           VARCHAR(20) NOT NULL,
    RAD_OPPRETTET        TIMESTAMP NOT NULL,
    RAD_OPPDATERT        TIMESTAMP NOT NULL
);

CREATE INDEX AKTIVITET_PKEY_INDEX ON KAFKA_AKTIVITET_MELDING(AKTIVITET_ID);
CREATE INDEX AKTOR_AKTIVITET_INDEX ON KAFKA_AKTIVITET_MELDING(AKTOR_ID);