DROP TABLE IF EXISTS LEST_ARENA_HENDELSE;

CREATE TABLE IF NOT EXISTS LEST_ARENA_HENDELSE_AKTIVITET
(
    AKTIVITETID VARCHAR(25) NOT NULL,
    HENDELSE_ID bigint,
    PRIMARY KEY (AKTIVITETID)
);

CREATE TABLE IF NOT EXISTS LEST_ARENA_HENDELSE_YTELSE
(
    VEDTAKID    VARCHAR(25) NOT NULL,
    HENDELSE_ID bigint,
    PRIMARY KEY (VEDTAKID)
);