CREATE TABLE SISTE_ENDRING
(
    AKTOERID                VARCHAR(20) NOT NULL,
    AKTIVITETID             VARCHAR(20),
    SISTE_ENDRING_KATEGORI  VARCHAR(45),
    SISTE_ENDRING_TIDSPUNKT TIMESTAMP,
    ER_SETT                 boolean default false,
    PRIMARY KEY (AKTOERID, SISTE_ENDRING_KATEGORI)
);