-- Index på arbeidsliste_enhet ble ikke tatt i bruk
DROP INDEX arbeidsliste_enhet;

-- Arbeidsliste kommentar skal ikke mappes inn i opensearch
CREATE VIEW aktorid_indeksert_data AS
SELECT OD.AKTOERID,
       OD.OPPFOLGING,
       OD.STARTDATO,
       OD.NY_FOR_VEILEDER,
       OD.VEILEDERID,
       OD.MANUELL,
       D.VENTER_PA_BRUKER,
       D.VENTER_PA_NAV,
       V.VEDTAKSTATUS,
       BP.PROFILERING_RESULTAT,
       CV.HAR_DELT_CV,
       CV.CV_EKSISTERER,
       BR.BRUKERS_SITUASJON,
       BR.UTDANNING,
       BR.UTDANNING_BESTATT,
       BR.UTDANNING_GODKJENT,
       V.ANSVARLIG_VEILDERNAVN          as VEDTAKSTATUS_ANSVARLIG_VEILDERNAVN,
       V.ENDRET_TIDSPUNKT               as VEDTAKSTATUS_ENDRET_TIDSPUNKT,
       ARB.SIST_ENDRET_AV_VEILEDERIDENT as ARB_SIST_ENDRET_AV_VEILEDERIDENT,
       ARB.ENDRINGSTIDSPUNKT            as ARB_ENDRINGSTIDSPUNKT,
       ARB.OVERSKRIFT                   as ARB_OVERSKRIFT,
       ARB.FRIST                        as ARB_FRIST,
       ARB.KATEGORI                     as ARB_KATEGORI

FROM OPPFOLGING_DATA OD
         LEFT JOIN DIALOG D ON D.AKTOERID = OD.AKTOERID
         LEFT JOIN VEDTAKSTATUS V on V.AKTOERID = OD.AKTOERID
         LEFT JOIN ARBEIDSLISTE ARB on ARB.AKTOERID = OD.AKTOERID
         LEFT JOIN BRUKER_PROFILERING BP ON BP.AKTOERID = OD.AKTOERID
         LEFT JOIN BRUKER_CV CV on CV.AKTOERID = OD.AKTOERID
         LEFT JOIN BRUKER_REGISTRERING BR on BR.AKTOERID = OD.AKTOERID;