CREATE TABLE AKTIVITETER
(
    AKTIVITETID   VARCHAR(20),
    AKTOERID      VARCHAR(20) NOT NULL,
    AKTIVITETTYPE VARCHAR(255),
    AVTALT        boolean default true,
    FRADATO       TIMESTAMP,
    TILDATO       TIMESTAMP,
    STATUS        VARCHAR(255),
    VERSION       bigint,
    PRIMARY KEY (AKTIVITETID)
);

CREATE TABLE AKTIVITETTYPE_STATUS_FOR_BRUKER
(
    AKTOERID         VARCHAR(20) NOT NULL,
    AKTIVITETTYPE    VARCHAR(255),
    NESTE_UTLOPSDATO TIMESTAMP,
    NESTE_STARTDATO  TIMESTAMP,
    AKTIV            boolean default false,
    PRIMARY KEY (AKTOERID, AKTIVITETTYPE)
);

CREATE TABLE AKTIVITET_STATUS_FOR_BRUKER
(
    AKTOERID                VARCHAR(20) NOT NULL,
    NYESTEUTLOPTEAKTIVITET  TIMESTAMP,
    FORRIGE_AKTIVITET_START TIMESTAMP,
    AKTIVITET_START         TIMESTAMP,
    NESTE_AKTIVITET_START   TIMESTAMP,
    PRIMARY KEY (AKTOERID)
);

CREATE TABLE GRUPPE_AKTIVITER
(
    MOTEPLAN_ID           VARCHAR(25) NOT NULL,
    VEILEDNINGDELTAKER_ID VARCHAR(25) NOT NULL,

    AKTOERID              VARCHAR(20),
    MOTEPLAN_STARTDATO    TIMESTAMP,
    MOTEPLAN_SLUTTDATO    TIMESTAMP,
    HENDELSE_ID           bigint,
    AKTIV                 boolean default false,
    PRIMARY KEY (MOTEPLAN_ID, VEILEDNINGDELTAKER_ID)
);

CREATE INDEX AKTOERID_GRUPPE_AKTIVITER_IDX ON GRUPPE_AKTIVITER (AKTOERID);