CREATE TABLE PDL_IDENTER
(
    BRUKER_NR BIGSERIAL,
    IDENT     VARCHAR(30) NOT NULL,
    HISTORISK BOOLEAN     NOT NULL,
    GRUPPE    VARCHAR(30) NOT NULL,

    PRIMARY KEY (BRUKER_NR, IDENT, GRUPPE)
);

CREATE SEQUENCE PDL_BRUKER_SEQ AS BIGINT START 0;