CREATE TABLE NOM_SKJERMING
(
    FODSELSNR    VARCHAR(33) NOT NULL,
    ER_SKJERMET  BOOLEAN   DEFAULT false,
    SKJERMET_FRA TIMESTAMP DEFAULT NULL,
    SKJERMET_TIL TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (FODSELSNR)
);