ALTER TABLE BRUKER_STATSBORGERSKAP
    DROP CONSTRAINT fk_freg_ident;
ALTER TABLE BRUKER_STATSBORGERSKAP
    ADD CONSTRAINT fk_freg_ident FOREIGN KEY (FREG_IDENT) REFERENCES BRUKER_DATA (freg_ident) ON
        DELETE CASCADE;