CREATE TABLE BRUKER_DATA
(
    FREG_IDENT   VARCHAR(30) NOT NULL,
    FORNAVN      VARCHAR(90),
    MELLOMNAVN   VARCHAR(90),
    ETTERNAVN    VARCHAR(90),
    KJOENN       VARCHAR(5),
    ER_DOED      BOOLEAN,
    FOEDSELSDATO DATE,

    PRIMARY KEY (FREG_IDENT)
);