CREATE TABLE BRUKER_DATA
(
    FNR           VARCHAR(30) NOT NULL,
    FORNAVN       VARCHAR(90),
    ETTERNAVN     VARCHAR(90),
    MELLOMNAVN    VARCHAR(90),
    KJOENN        VARCHAR(10),
    ER_DOED       BOOLEAN,
    FOEDSELS_DATO DATE,

    PRIMARY KEY (FNR)
);