CREATE TABLE BRUKER_STATSBORGERSKAP
(
    FREG_IDENT      VARCHAR(30) NOT NULL,
    STATSBORGERSKAP VARCHAR(20),
    GYLDIG_FRA      VARCHAR(90),
    GYLDIG_TIL      VARCHAR(90),

    PRIMARY KEY (FREG_IDENT)
);