CREATE TABLE SISTE_14A_VEDTAK
(
    BRUKER_ID     VARCHAR(20) NOT NULL,
    HOVEDMAL      VARCHAR(30),
    INNSATSGRUPPE VARCHAR(40) NOT NULL,
    FATTET_DATO   TIMESTAMP WITH TIME ZONE NOT NULL,
    FRA_ARENA     BOOLEAN NOT NULL,

    PRIMARY KEY (BRUKER_ID)
)
