CREATE TABLE SISTE_14A_VEDTAK
(
    AKTOR_ID      VARCHAR(20) NOT NULL,
    HOVEDMAL      VARCHAR(30),
    INNSATSGRUPPE VARCHAR(40) NOT NULL,
    FATTET_DATO   TIMESTAMP WITH TIME ZONE NOT NULL,

    PRIMARY KEY (AKTOR_ID)
)
