ALTER TABLE ytelsesvedtak
    ADD COLUMN ANTALLDAGERIGJEN INTEGER;

ALTER TABLE ytelsesvedtak
    ADD COLUMN OPPDATERT TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE YTELSE_STATUS_FOR_BRUKER
    ADD COLUMN ANTALLDAGERIGJEN INTEGER;

ALTER TABLE YTELSE_STATUS_FOR_BRUKER
    ADD COLUMN OPPDATERT TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL;



