CREATE TABLE BRUKER_BARN_RELASJON
(
    FORESATT_IDENT        VARCHAR(30) NOT NULL,
    BARN_IDENT            VARCHAR(30) NOT NULL,
    FORESATT_ER_ANSVARLIG BOOLEAN,
    PRIMARY KEY (FORESATT_IDENT, BARN_IDENT)
);

CREATE TABLE BARN_DATA
(
    IDENT          VARCHAR(30) NOT NULL,
    FOEDSELSDATO   DATE        NOT NULL,
    DISKRESJONKODE VARCHAR(3),
    PRIMARY KEY (IDENT)
);


ALTER TABLE BRUKER_BARN_RELASJON
    ADD CONSTRAINT FK_PERSON_IDENT FOREIGN KEY (FORESATT_IDENT) REFERENCES BRUKER_DATA (FREG_IDENT) ON DELETE CASCADE;

ALTER TABLE BRUKER_BARN_RELASJON
    ADD CONSTRAINT FK_BARN_IDENT FOREIGN KEY (BARN_IDENT) REFERENCES BARN_DATA (IDENT) ON DELETE CASCADE;



