CREATE TABLE BRUKERTILTAK_NY_KILDE
(
    AKTIVITETID VARCHAR(25) NOT NULL,
    AKTOERID    VARCHAR(20),
    PERSONID    VARCHAR(20),
    TILTAKSKODE VARCHAR(10),
    TILDATO     TIMESTAMP,
    FRADATO     TIMESTAMP,
    VERSION     BIGINT,

    PRIMARY KEY (AKTIVITETID)
);
CREATE INDEX BRUKERTILTAK_NY_KILDE_AKTOERID_INDEX ON BRUKERTILTAK (AKTOERID);
