DROP TABLE bruker_data_barn;

CREATE TABLE BRUKER_DATA_BARN
(
    BARN_IDENT      VARCHAR(30) NOT NULL PRIMARY KEY,
    BARN_FOEDSELSDATO   DATE        NOT NULL,
    BARN_DISKRESJONKODE VARCHAR(3)
);

CREATE TABLE FORELDREANSVAR
(
    FORESATT_IDENT      VARCHAR(30) NOT NULL,
    BARN_IDENT      VARCHAR(30) NOT NULL,
    PRIMARY KEY (FORESATT_IDENT, BARN_IDENT)
);

ALTER TABLE FORELDREANSVAR
    ADD CONSTRAINT FK_FORESATT_IDENT FOREIGN KEY (FORESATT_IDENT) REFERENCES BRUKER_DATA (FREG_IDENT) ON DELETE CASCADE;
