ALTER TABLE ytelsesvedtak
    ALTER COLUMN ENDRET_DATO DROP DEFAULT;
ALTER TABLE ytelsesvedtak
    ALTER COLUMN ENDRET_DATO DROP NOT NULL;

ALTER TABLE YTELSE_STATUS_FOR_BRUKER
    ALTER COLUMN ENDRET_DATO DROP DEFAULT;
ALTER TABLE YTELSE_STATUS_FOR_BRUKER
    ALTER COLUMN ENDRET_DATO DROP NOT NULL;



