CREATE TABLE BRUKER_DATA_BARN
(
    ID                  SERIAL PRIMARY KEY,
    FORESATT_IDENT      VARCHAR(30) NOT NULL,
    BOR_MED_FORESATT    BOOLEAN,
    BARN_FOEDSELSDATO   DATE        NOT NULL,
    BARN_DISKRESJONKODE VARCHAR(3)
);

CREATE INDEX IDX_BRUKER_DATA_BARN_FORESATT_IDENT
    ON BRUKER_DATA_BARN (FORESATT_IDENT);

ALTER TABLE BRUKER_DATA_BARN
    ADD CONSTRAINT FK_FREG_IDENT FOREIGN KEY (FORESATT_IDENT) REFERENCES BRUKER_DATA (FREG_IDENT) ON DELETE CASCADE;



