CREATE TABLE FARGEKATEGORI
(
    ID                           UUID PRIMARY KEY NOT NULL,
    FNR                          VARCHAR(11) NOT NULL,
    VERDI                        VARCHAR(25),
    SIST_ENDRET                  TIMESTAMP NOT NULL,
    SIST_ENDRET_AV_VEILEDERIDENT VARCHAR(7)
);

CREATE INDEX FARGEKATEGORI_FNR_INDEX ON FARGEKATEGORI (FNR);
