CREATE TABLE OPPLYSNINGER_OM_ARBEIDSSOEKER
(
    ID                               SERIAL PRIMARY KEY,
    OPPLYSNINGER_OM_ARBEIDSSOEKER_ID UUID UNIQUE NOT NULL,
    PERIODE_ID                       UUID        NOT NULL,
    SENDT_INN_TIDSPUNKT              TIMESTAMP   NOT NULL,
    UTDANNING_NUS_KODE               CHAR(1),
    UTDANNING_BESTATT                VARCHAR(8),
    UTDANNING_GODKJENT               VARCHAR(8)
);

CREATE TABLE OPPLYSNINGER_OM_ARBEIDSSOEKER_JOBBSITUASJON
(
    ID                               SERIAL PRIMARY KEY,
    OPPLYSNINGER_OM_ARBEIDSSOEKER_ID UUID REFERENCES OPPLYSNINGER_OM_ARBEIDSSOEKER (OPPLYSNINGER_OM_ARBEIDSSOEKER_ID) ON DELETE CASCADE NOT NULL,
    JOBBSITUASJON                    VARCHAR(255)                                                                                       NOT NULL
);
