CREATE TABLE OPPFOLGING_DATA_V2
(
    AKTOERID        VARCHAR(20) NOT NULL,
    VEILEDERID      VARCHAR(20),
    OPPFOLGING      boolean DEFAULT false NOT NULL,
    NY_FOR_VEILEDER boolean DEFAULT false NOT NULL,
    MANUELL         boolean DEFAULT false NOT NULL,
    STARTDATO       TIMESTAMP,
    TILORDNET_DATO  TIMESTAMP,

    PRIMARY KEY (AKTOERID)
);

CREATE INDEX OPPFOLGING_DATA_V2_IDX ON OPPFOLGING_DATA_V2 (VEILEDERID);
CREATE INDEX OPPFOLGING_DATA_V2_OPPFOLGING_IDX ON OPPFOLGING_DATA_V2 (OPPFOLGING);
