package no.nav.fo.veilarbportefolje.domene;

public enum Brukerstatus {
    NYE_BRUKERE, TRENGER_VURDERING, UFORDELTE_BRUKERE, INAKTIVE_BRUKERE, VENTER_PA_SVAR_FRA_NAV, VENTER_PA_SVAR_FRA_BRUKER,
    UTLOPTE_AKTIVITETER, IKKE_I_AVTALT_AKTIVITET, I_AVTALT_AKTIVITET, MIN_ARBEIDSLISTE, NYE_BRUKERE_FOR_VEILEDER, ER_SYKMELDT_MED_ARBEIDSGIVER
}
