package no.nav.pto.veilarbportefolje.persononinfo;

import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class SpraakKode {
    private static Map<String, String> spraak = Stream.of(new String[][]{
            {"AA", "Afar"},
            {"AB", "Abkhazian"},
            {"AB", "Abkhazian"},
            {"AB", "Abkhasisk"},
            {"AE", "Avestan"},
            {"AE", "Avestan"},
            {"AE", "Avestisk"},
            {"AF", "Afrikaans"},
            {"AF", "Afrikaans"},
            {"AK", "Akan"},
            {"AK", "Akan"},
            {"AM", "Amharic"},
            {"AM", "Amharic"},
            {"AM", "Amharisk"},
            {"AN", "Aragonesisk"},
            {"AN", "Aragonese"},
            {"AN", "Aragonese"},
            {"AR", "Arabisk"},
            {"AR", "Arabic"},
            {"AR", "Arabic"},
            {"AS", "Assamese"},
            {"AS", "Assamese"},
            {"AS", "Assamesisk"},
            {"AV", "Avarisk"},
            {"AV", "Avaric"},
            {"AV", "Avaric"},
            {"AY", "Aymara"},
            {"AY", "Aymara"},
            {"AZ", "Azerbaijani"},
            {"AZ", "Azerbaijani"},
            {"AZ", "Aserbajdsjansk"},
            {"BA", "Basjkirsk"},
            {"BA", "Bashkir"},
            {"BA", "Bashkir"},
            {"BE", "Hviterussisk"},
            {"BE", "Belarusian"},
            {"BE", "Belarusian"},
            {"BG", "Bulgarian"},
            {"BG", "Bulgarsk"},
            {"BG", "Bulgarian"},
            {"BH", "Bihari"},
            {"BH", "Bihari"},
            {"BI", "Bislama"},
            {"BI", "Bislama"},
            {"BM", "Bambara"},
            {"BM", "Bambara"},
            {"BN", "Bengali"},
            {"BN", "Bengali"},
            {"BO", "Tibetan"},
            {"BO", "Tibetansk"},
            {"BO", "Tibetan"},
            {"BR", "Breton"},
            {"BR", "Bretonsk"},
            {"BR", "Breton"},
            {"BS", "Bosnian"},
            {"BS", "Bosnian"},
            {"BS", "Bosnisk"},
            {"BX", "Badini"},
            {"BY", "Bilen"},
            {"CA", "Katalansk"},
            {"CA", "Catalan, Valencian"},
            {"CA", "Catalan, Valencian"},
            {"CE", "Chechen"},
            {"CE", "Chechen"},
            {"CE", "Tsjetsjensk"},
            {"CH", "Chamorro"},
            {"CH", "Chamorro"},
            {"CO", "Corsican"},
            {"CO", "Korsiansk"},
            {"CO", "Corsican"},
            {"CR", "Cree"},
            {"CR", "Cree"},
            {"CS", "Tsjekkisk"},
            {"CS", "Czech"},
            {"CS", "Czech"},
            {"CU", "Kirkeslavisk"},
            {"CU", "Church Slavic, Old Slavonic,Church Slavonic, O"},
            {"CV", "Tsjuvasjisk"},
            {"CV", "Chuvash"},
            {"CV", "Chuvash"},
            {"CX", "Hakha Chin"},
            {"CY", "Welsh"},
            {"CY", "Walisisk"},
            {"CY", "Welsh"},
            {"DA", "Dansk"},
            {"DA", "Danish"},
            {"DA", "Danish"},
            {"DE", "German"},
            {"DE", "Tysk"},
            {"DE", "German"},
            {"DV", "Divehi"},
            {"DV", "Dhivehi"},
            {"DV", "Divehi"},
            {"DX", "Dari"},
            {"DZ", "Dzongkha"},
            {"DZ", "Dzongkha"},
            {"EE", "Ewe"},
            {"EE", "Ewe"},
            {"EL", "Greek, Modern (1453-)"},
            {"EL", "Gresk"},
            {"EL", "Greek, Modern (1453-)"},
            {"EN", "English"},
            {"EN", "English"},
            {"EN", "Engelsk"},
            {"EO", "Esperanto"},
            {"EO", "Esperanto"},
            {"ES", "Spanish, Castilian"},
            {"ES", "Spansk"},
            {"ES", "Spanish, Castilian"},
            {"ET", "Estonian"},
            {"ET", "Estonian"},
            {"ET", "Estisk"},
            {"EU", "Basque"},
            {"EU", "Baskisk"},
            {"EU", "Basque"},
            {"FA", "Persian"},
            {"FA", "Persian"},
            {"FA", "Persisk"},
            {"FF", "Fulfulde"},
            {"FF", "Fulah"},
            {"FF", "Fulah"},
            {"FI", "Finnish"},
            {"FI", "Finnish"},
            {"FI", "Finsk"},
            {"FJ", "Fijian"},
            {"FJ", "Fijian"},
            {"FJ", "Fijisk"},
            {"FO", "Faroese"},
            {"FO", "Færøysk"},
            {"FO", "Faroese"},
            {"FR", "Fransk"},
            {"FR", "French"},
            {"FR", "French"},
            {"FY", "Frisian"},
            {"FY", "Frisian"},
            {"GA", "Irish"},
            {"GA", "Irsk"},
            {"GA", "Irish"},
            {"GD", "Gaelic, Scottish Gaelic"},
            {"GD", "Skotsk gælisk"},
            {"GD", "Gaelic, Scottish Gaelic"},
            {"GL", "Gallegan"},
            {"GL", "Galisisk"},
            {"GL", "Gallegan"},
            {"GN", "Guarani"},
            {"GN", "Guarani"},
            {"GU", "Gujarati"},
            {"GU", "Gujarati"},
            {"GV", "Manx"},
            {"GV", "Mansk"},
            {"GV", "Manx"},
            {"HA", "Hausa"},
            {"HA", "Hausa"},
            {"HE", "Hebrew"},
            {"HE", "Hebrew"},
            {"HE", "Hebraisk"},
            {"HI", "Hindi"},
            {"HI", "Hindi"},
            {"HO", "Hiri Motu"},
            {"HO", "Hiri Motu"},
            {"HR", "Croatian"},
            {"HR", "Croatian"},
            {"HR", "Kroatisk"},
            {"HT", "Haitisk kreolsk"},
            {"HT", "Haitian, Haitian Creole"},
            {"HT", "Haitian, Haitian Creole"},
            {"HU", "Hungarian"},
            {"HU", "Ungarsk"},
            {"HU", "Hungarian"},
            {"HX", "Hazaragi"},
            {"HY", "Armenian"},
            {"HY", "Armenian"},
            {"HY", "Armensk"},
            {"HZ", "Herero"},
            {"HZ", "Herero"},
            {"IA", "Interlingua (International Auxili"},
            {"IA", "Interlingua (International Auxili"},
            {"ID", "Indonesisk"},
            {"ID", "Indonesian"},
            {"ID", "Indonesian"},
            {"IE", "Interlingue"},
            {"IE", "Interlingue"},
            {"IG", "Igbo"},
            {"IG", "Igbo"},
            {"II", "Sichuan Yi"},
            {"II", "Yi"},
            {"II", "Sichuan Yi"},
            {"IK", "Inupiaq"},
            {"IK", "Inupiak"},
            {"IK", "Inupiaq"},
            {"IO", "Ido"},
            {"IO", "Ido"},
            {"IS", "Icelandic"},
            {"IS", "Islandsk"},
            {"IS", "Icelandic"},
            {"IT", "Italiensk"},
            {"IT", "Italian"},
            {"IT", "Italian"},
            {"IU", "Inuktitut"},
            {"IU", "Inuktitut"},
            {"IU", "Inuittisk"},
            {"JA", "Japanese"},
            {"JA", "Japansk"},
            {"JA", "Japanese"},
            {"JV", "Javanese"},
            {"JV", "Javanesisk"},
            {"JV", "Javanese"},
            {"KA", "Georgisk"},
            {"KA", "Georgian"},
            {"KA", "Georgian"},
            {"KG", "Kongo"},
            {"KG", "Kongo"},
            {"KG", "Kongo"},
            {"KG", "Kongolesisk"},
            {"KI", "Kikuyu, Gikuyu"},
            {"KI", "Kikuyu, Gikuyu"},
            {"KI", "Kikuyu"},
            {"KJ", "Kuanyama, Kwanyama"},
            {"KJ", "Kuanyama, Kwanyama"},
            {"KJ", "Kwanyama"},
            {"KK", "Kazakh"},
            {"KK", "Kasakhisk"},
            {"KK", "Kazakh"},
            {"KL", "Kalaallisut, Greenlandic"},
            {"KL", "Kalaallisut, Greenlandic"},
            {"KL", "Kalaallisut"},
            {"KM", "Khmer"},
            {"KM", "Khmer"},
            {"KN", "Kannada"},
            {"KN", "Kannada"},
            {"KO", "Korean"},
            {"KO", "Korean"},
            {"KO", "Koreansk"},
            {"KR", "Kanuri"},
            {"KR", "Kanuri"},
            {"KS", "Kashmiri"},
            {"KS", "Kashmiri"},
            {"KU", "Kurdish"},
            {"KU", "Kurdish"},
            {"KU", "Kurdisk"},
            {"KV", "Komi"},
            {"KV", "Syrjensk"},
            {"KV", "Komi"},
            {"KW", "Kornisk"},
            {"KW", "Cornish"},
            {"KW", "Cornish"},
            {"KX", "Kurmanci"},
            {"KY", "Kirgisisk"},
            {"KY", "Kirghiz"},
            {"KY", "Kirghiz"},
            {"KZ", "Karen"},
            {"LA", "Latin"},
            {"LA", "Latin"},
            {"LB", "Luxembourgsk"},
            {"LB", "Luxembourgish, Letzeburgesch"},
            {"LB", "Luxembourgish, Letzeburgesch"},
            {"LG", "Ganda"},
            {"LG", "Luganda"},
            {"LG", "Ganda"},
            {"LI", "Limburgisk"},
            {"LI", "Limburgan, Limburger, Limburgish"},
            {"LI", "Limburgan, Limburger, Limburgish"},
            {"LN", "Lingala"},
            {"LN", "Lingala"},
            {"LO", "Laotisk"},
            {"LO", "Lao"},
            {"LO", "Lao"},
            {"LT", "Lithuanian"},
            {"LT", "Litauisk"},
            {"LT", "Lithuanian"},
            {"LU", "Luba-Katanga"},
            {"LU", "Luba-Katanga"},
            {"LV", "Latvian"},
            {"LV", "Latvian"},
            {"LV", "Latvisk"},
            {"MG", "Malagasy"},
            {"MG", "Gassisk"},
            {"MG", "Malagasy"},
            {"MH", "Marshallesisk"},
            {"MH", "Marshallese"},
            {"MH", "Marshallese"},
            {"MI", "Maori"},
            {"MI", "Maorisk"},
            {"MI", "Maori"},
            {"MK", "Makedonsk"},
            {"MK", "Macedonian"},
            {"MK", "Macedonian"},
            {"ML", "Malayalam"},
            {"ML", "Malayalam"},
            {"MN", "Mongolian"},
            {"MN", "Mongolian"},
            {"MN", "Mongolsk"},
            {"MO", "Moldavian"},
            {"MO", "Moldavian"},
            {"MO", "Moldovsk"},
            {"MR", "Marathi"},
            {"MR", "Marathi"},
            {"MS", "Malay"},
            {"MS", "Malay"},
            {"MS", "Malayisk"},
            {"MT", "Maltese"},
            {"MT", "Maltese"},
            {"MT", "Maltesisk"},
            {"MY", "Burmese"},
            {"MY", "Burmese"},
            {"MY", "Burmesisk"},
            {"NA", "Nauru"},
            {"NA", "Nauru"},
            {"NA", "Naurisk"},
            {"NB", "Norwegian BokmÕl, BokmÕl, Norwegian"},
            {"NB", "Norwegian BokmÕl, BokmÕl, Norwegian"},
            {"NB", "Norwegian"},
            {"NB", "Norsk"},
            {"NB", "Norwegian BokmÕl, BokmÕl, Norwegian"},
            {"ND", "Ndebele, North, North Ndebele"},
            {"ND", "Ndebele, North, North Ndebele"},
            {"ND", "Nord-ndebele"},
            {"NE", "Nepali"},
            {"NE", "Nepali"},
            {"NG", "Ndonga"},
            {"NG", "Ndonga"},
            {"NL", "Nederlandsk"},
            {"NL", "Dutch, Flemish"},
            {"NL", "Dutch, Flemish"},
            {"NN", "Norwegian Nynorsk, Nynorsk, Norwegian"},
            {"NN", "Norwegian Nynorsk, Nynorsk, Norwegian"},
            {"NN", "Nynorsk"},
            {"NO", "Norwegian"},
            {"NO", "Norwegian"},
            {"NO", "Norsk"},
            {"NR", "Sør-ndebele"},
            {"NR", "Ndebele, South, South Ndebele"},
            {"NR", "Ndebele, South, South Ndebele"},
            {"NV", "Navajo"},
            {"NV", "Navajo, Navaho"},
            {"NV", "Navajo, Navaho"},
            {"NY", "Chichewa, Chewa, Nyanja"},
            {"NY", "Chichewa, Chewa, Nyanja"},
            {"NY", "Chichewa"},
            {"OC", "Oksitansk"},
            {"OC", "Occitan (post 1500), Provenþal"},
            {"OC", "Occitan (post 1500), Provenþal"},
            {"OJ", "Ojibwa"},
            {"OJ", "Ojibwa"},
            {"OM", "Oromo"},
            {"OM", "Oromo"},
            {"OR", "Oriya"},
            {"OR", "Oriya"},
            {"OS", "Ossetian, Ossetic"},
            {"OS", "Ossetian, Ossetic"},
            {"OS", "Ossetisk"},
            {"PA", "Panjabi, Punjabi"},
            {"PA", "Punjabi"},
            {"PA", "Panjabi, Punjabi"},
            {"PI", "Pali"},
            {"PI", "Pali"},
            {"PL", "Polish"},
            {"PL", "Polsk"},
            {"PL", "Polish"},
            {"PS", "Pushto"},
            {"PS", "Pushto"},
            {"PT", "Portuguese"},
            {"PT", "Portuguese"},
            {"PT", "Portugesisk"},
            {"QU", "Quechua"},
            {"QU", "Quechua"},
            {"RM", "Raeto-Romance"},
            {"RM", "Retoromansk"},
            {"RM", "Raeto-Romance"},
            {"RN", "Rundi"},
            {"RN", "Rundi"},
            {"RN", "Kirundi"},
            {"RO", "Rumesk"},
            {"RO", "Romanian"},
            {"RO", "Romanian"},
            {"RU", "Russisk"},
            {"RU", "Russian"},
            {"RU", "Russian"},
            {"RW", "Kinyarwanda"},
            {"RW", "Kinyarwanda"},
            {"SA", "Sanskrit"},
            {"SA", "Sanskrit"},
            {"SC", "Sardinian"},
            {"SC", "Sardinian"},
            {"SC", "Sardisk"},
            {"SD", "Sindhi"},
            {"SD", "Sindhi"},
            {"SE", "Nord Samisk"},
            {"SE", "Northern Sami"},
            {"SE", "Northern Sami"},
            {"SG", "Sango"},
            {"SG", "Sango"},
            {"SI", "Sinhala, Sinhalese"},
            {"SI", "Singalesisk"},
            {"SI", "Sinhala, Sinhalese"},
            {"SI", "Sinhala, Sinhalese"},
            {"SI", "Sinhala, Sinhalese"},
            {"SK", "Slovak"},
            {"SK", "Slovak"},
            {"SK", "Slovakisk"},
            {"SL", "Slovenian"},
            {"SL", "Slovenian"},
            {"SL", "Slovensk"},
            {"SM", "Samoan"},
            {"SM", "Samoan"},
            {"SM", "Samoansk"},
            {"SN", "Shona"},
            {"SN", "Shona"},
            {"SO", "Somali"},
            {"SO", "Somalisk"},
            {"SO", "Somali"},
            {"SQ", "Albanian"},
            {"SQ", "Albanian"},
            {"SQ", "Albansk"},
            {"SR", "Serbisk"},
            {"SR", "Serbian"},
            {"SR", "Serbian"},
            {"SS", "Swati"},
            {"SS", "Swati"},
            {"ST", "Sesotho"},
            {"ST", "Sotho, Southern"},
            {"ST", "Sotho, Southern"},
            {"SU", "Sundanese"},
            {"SU", "Sudanesisk"},
            {"SU", "Sundanese"},
            {"SV", "Svensk"},
            {"SV", "Swedish"},
            {"SV", "Swedish"},
            {"SW", "Swahili"},
            {"SW", "Swahili"},
            {"SX", "Sorani"},
            {"TA", "Tamil"},
            {"TA", "Tamil"},
            {"TA", "Tamilsk"},
            {"TE", "Telugu"},
            {"TE", "Telugu"},
            {"TG", "Tajik"},
            {"TG", "Tadsjikisk"},
            {"TG", "Tajik"},
            {"TH", "Thai"},
            {"TH", "Thai"},
            {"TI", "Tigrinya"},
            {"TI", "Tigrinya"},
            {"TK", "Turkmen"},
            {"TK", "Turkmen"},
            {"TK", "Turkmensk"},
            {"TL", "Tagalog"},
            {"TL", "Tagalog"},
            {"TN", "Tswana"},
            {"TN", "Tswana"},
            {"TO", "Tonganesisk"},
            {"TO", "Tonga (Tonga Islands)"},
            {"TO", "Tonga (Tonga Islands)"},
            {"TR", "Turkish"},
            {"TR", "Tyrkisk"},
            {"TR", "Turkish"},
            {"TS", "Tsonga"},
            {"TS", "Tsonga"},
            {"TT", "Tatar"},
            {"TT", "Tatar"},
            {"TT", "Tatarsk"},
            {"TW", "Twi"},
            {"TW", "Twi"},
            {"TY", "Tahitian"},
            {"TY", "Tahitian"},
            {"TY", "Tahitisk"},
            {"UG", "Uighur, Uyghur"},
            {"UG", "Uighur, Uyghur"},
            {"UG", "Uigurisk"},
            {"UK", "Ukrainsk"},
            {"UK", "Ukrainian"},
            {"UK", "Ukrainian"},
            {"UR", "Urdu"},
            {"UR", "Urdu"},
            {"UZ", "Uzbek"},
            {"UZ", "Uzbek"},
            {"UZ", "Usbekisk"},
            {"VE", "Venda"},
            {"VE", "Tshivenda"},
            {"VE", "Venda"},
            {"VI", "Vietnamese"},
            {"VI", "Vietnamese"},
            {"VI", "Vietnamesisk"},
            {"VO", "Volapük"},
            {"WA", "Vallonsk"},
            {"WA", "Walloon"},
            {"WA", "Walloon"},
            {"WO", "Wolof"},
            {"WO", "Wolof"},
            {"XH", "Xhosa"},
            {"XH", "Xhosa"},
            {"YI", "Jiddisk"},
            {"YI", "Yiddish"},
            {"YI", "Yiddish"},
            {"YO", "Yoruba"},
            {"YO", "Joruba"},
            {"YO", "Yoruba"},
            {"YX", "Kantonesisk/Yue"},
            {"ZA", "Zhuang, Chuang"},
            {"ZA", "Zhuang"},
            {"ZH", "Chinese"},
            {"ZH", "Kinesisk"},
            {"ZU", "Zulu"},
            {"ZU", "Zulu"}
    }).collect(Collectors.toMap(data -> data[0], data -> data[1]));

    public static String getSpraak(String spraakCode) {
        if (spraakCode == null || spraakCode.isEmpty()) {
            return null;
        }

        return spraak.getOrDefault(spraakCode, "");
    }
}
