package no.nav.pto.veilarbportefolje.domene;

//TODO DENNE KAN SLETTES ETTER VEDTAKSTOTTE ER PÅLUFTA -> DÅ BRUKER VI PROFILERINGSRESULTAT ENUM
public enum VurderingsBehov {
    ARBEIDSEVNE_VURDERING, IKKE_VURDERT, ANTATT_GODE_MULIGHETER, ANTATT_BEHOV_FOR_VEILEDNING, OPPGITT_HINDRINGER
}
