//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-***REMOVED***.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.09 at 11:38:41 AM CET 
//


package no.nav.fo.loependeytelser;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * <p>Java class for AAPtellere complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AAPtellere">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="antallUkerIgjen" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="antallDagerIgjen" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="antallDagerUnntak" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="antallDagerIgjenUnntak" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AAPtellere", propOrder = {
    "antallUkerIgjen",
    "antallDagerIgjen",
    "antallDagerUnntak",
    "antallDagerIgjenUnntak"
})
public class AAPtellere {

    @XmlElement(required = true)
    protected BigInteger antallUkerIgjen;
    @XmlElement(required = true)
    protected BigInteger antallDagerIgjen;
    protected BigInteger antallDagerUnntak;
    protected BigInteger antallDagerIgjenUnntak;

    /**
     * Gets the value of the antallUkerIgjen property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAntallUkerIgjen() {
        return antallUkerIgjen;
    }

    /**
     * Sets the value of the antallUkerIgjen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAntallUkerIgjen(BigInteger value) {
        this.antallUkerIgjen = value;
    }

    /**
     * Gets the value of the antallDagerIgjen property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAntallDagerIgjen() {
        return antallDagerIgjen;
    }

    /**
     * Sets the value of the antallDagerIgjen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAntallDagerIgjen(BigInteger value) {
        this.antallDagerIgjen = value;
    }

    /**
     * Gets the value of the antallDagerUnntak property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAntallDagerUnntak() {
        return antallDagerUnntak;
    }

    /**
     * Sets the value of the antallDagerUnntak property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAntallDagerUnntak(BigInteger value) {
        this.antallDagerUnntak = value;
    }

    /**
     * Gets the value of the antallDagerIgjenUnntak property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAntallDagerIgjenUnntak() {
        return antallDagerIgjenUnntak;
    }

    /**
     * Sets the value of the antallDagerIgjenUnntak property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAntallDagerIgjenUnntak(BigInteger value) {
        this.antallDagerIgjenUnntak = value;
    }

}
