//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-***REMOVED***.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.09 at 11:38:41 AM CET 
//


package no.nav.fo.loependeytelser;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * <p>Java class for Dagpengetellere complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Dagpengetellere">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="antallUkerIgjen" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="antallDagerIgjen" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="antallUkerIgjenUnderPermittering" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="antallDagerIgjenUnderPermittering" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dagpengetellere", propOrder = {
    "antallUkerIgjen",
    "antallDagerIgjen",
    "antallUkerIgjenUnderPermittering",
    "antallDagerIgjenUnderPermittering"
})
public class Dagpengetellere {

    @XmlElement(required = true)
    protected BigInteger antallUkerIgjen;
    @XmlElement(required = true)
    protected BigInteger antallDagerIgjen;
    protected BigInteger antallUkerIgjenUnderPermittering;
    protected BigInteger antallDagerIgjenUnderPermittering;

    /**
     * Gets the value of the antallUkerIgjen property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAntallUkerIgjen() {
        return antallUkerIgjen;
    }

    /**
     * Sets the value of the antallUkerIgjen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAntallUkerIgjen(BigInteger value) {
        this.antallUkerIgjen = value;
    }

    /**
     * Gets the value of the antallDagerIgjen property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAntallDagerIgjen() {
        return antallDagerIgjen;
    }

    /**
     * Sets the value of the antallDagerIgjen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAntallDagerIgjen(BigInteger value) {
        this.antallDagerIgjen = value;
    }

    /**
     * Gets the value of the antallUkerIgjenUnderPermittering property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAntallUkerIgjenUnderPermittering() {
        return antallUkerIgjenUnderPermittering;
    }

    /**
     * Sets the value of the antallUkerIgjenUnderPermittering property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAntallUkerIgjenUnderPermittering(BigInteger value) {
        this.antallUkerIgjenUnderPermittering = value;
    }

    /**
     * Gets the value of the antallDagerIgjenUnderPermittering property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAntallDagerIgjenUnderPermittering() {
        return antallDagerIgjenUnderPermittering;
    }

    /**
     * Sets the value of the antallDagerIgjenUnderPermittering property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAntallDagerIgjenUnderPermittering(BigInteger value) {
        this.antallDagerIgjenUnderPermittering = value;
    }

}
