//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-***REMOVED***.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.09 at 11:38:41 AM CET 
//


package no.nav.fo.loependeytelser;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * <p>Java class for LoependeVedtak complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoependeVedtak">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="personident" type="{http://nav.no/melding/virksomhet/loependeYtelser/v1}Identifikator"/>
 *         &lt;element name="sakstypeKode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vedtakId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="rettighetstypeKode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vedtaksperiode" type="{http://nav.no/melding/virksomhet/loependeYtelser/v1}Periode"/>
 *         &lt;element name="dagpengetellere" type="{http://nav.no/melding/virksomhet/loependeYtelser/v1}Dagpengetellere" minOccurs="0"/>
 *         &lt;element name="aaptellere" type="{http://nav.no/melding/virksomhet/loependeYtelser/v1}AAPtellere" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoependeVedtak", propOrder = {
    "personident",
    "sakstypeKode",
    "vedtakId",
    "rettighetstypeKode",
    "vedtaksperiode",
    "dagpengetellere",
    "aaptellere"
})
public class LoependeVedtak {

    @XmlElement(required = true)
    protected String personident;
    @XmlElement(required = true)
    protected String sakstypeKode;
    @XmlElement(required = true)
    protected BigInteger vedtakId;
    @XmlElement(required = true)
    protected String rettighetstypeKode;
    @XmlElement(required = true)
    protected Periode vedtaksperiode;
    protected Dagpengetellere dagpengetellere;
    protected AAPtellere aaptellere;

    /**
     * Gets the value of the personident property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonident() {
        return personident;
    }

    /**
     * Sets the value of the personident property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonident(String value) {
        this.personident = value;
    }

    /**
     * Gets the value of the sakstypeKode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSakstypeKode() {
        return sakstypeKode;
    }

    /**
     * Sets the value of the sakstypeKode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSakstypeKode(String value) {
        this.sakstypeKode = value;
    }

    /**
     * Gets the value of the vedtakId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVedtakId() {
        return vedtakId;
    }

    /**
     * Sets the value of the vedtakId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVedtakId(BigInteger value) {
        this.vedtakId = value;
    }

    /**
     * Gets the value of the rettighetstypeKode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRettighetstypeKode() {
        return rettighetstypeKode;
    }

    /**
     * Sets the value of the rettighetstypeKode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRettighetstypeKode(String value) {
        this.rettighetstypeKode = value;
    }

    /**
     * Gets the value of the vedtaksperiode property.
     * 
     * @return
     *     possible object is
     *     {@link Periode }
     *     
     */
    public Periode getVedtaksperiode() {
        return vedtaksperiode;
    }

    /**
     * Sets the value of the vedtaksperiode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Periode }
     *     
     */
    public void setVedtaksperiode(Periode value) {
        this.vedtaksperiode = value;
    }

    /**
     * Gets the value of the dagpengetellere property.
     * 
     * @return
     *     possible object is
     *     {@link Dagpengetellere }
     *     
     */
    public Dagpengetellere getDagpengetellere() {
        return dagpengetellere;
    }

    /**
     * Sets the value of the dagpengetellere property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dagpengetellere }
     *     
     */
    public void setDagpengetellere(Dagpengetellere value) {
        this.dagpengetellere = value;
    }

    /**
     * Gets the value of the aaptellere property.
     * 
     * @return
     *     possible object is
     *     {@link AAPtellere }
     *     
     */
    public AAPtellere getAaptellere() {
        return aaptellere;
    }

    /**
     * Sets the value of the aaptellere property.
     * 
     * @param value
     *     allowed object is
     *     {@link AAPtellere }
     *     
     */
    public void setAaptellere(AAPtellere value) {
        this.aaptellere = value;
    }

}
