//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-***REMOVED***.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.09 at 11:38:41 AM CET 
//


package no.nav.fo.loependeytelser;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for LoependeYtelser complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoependeYtelser">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="loependeVedtakListe" type="{http://nav.no/melding/virksomhet/loependeYtelser/v1}LoependeVedtak" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="sakstypeListe" type="{http://nav.no/melding/virksomhet/loependeYtelser/v1}Sakstyper" maxOccurs="unbounded"/>
 *         &lt;element name="rettighetstypeListe" type="{http://nav.no/melding/virksomhet/loependeYtelser/v1}Rettighetstyper" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoependeYtelser", propOrder = {
    "loependeVedtakListe",
    "sakstypeListe",
    "rettighetstypeListe"
})
public class LoependeYtelser {

    protected List<LoependeVedtak> loependeVedtakListe;
    @XmlElement(required = true)
    protected List<Sakstyper> sakstypeListe;
    @XmlElement(required = true)
    protected List<Rettighetstyper> rettighetstypeListe;

    /**
     * Gets the value of the loependeVedtakListe property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the loependeVedtakListe property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLoependeVedtakListe().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LoependeVedtak }
     * 
     * 
     */
    public List<LoependeVedtak> getLoependeVedtakListe() {
        if (loependeVedtakListe == null) {
            loependeVedtakListe = new ArrayList<LoependeVedtak>();
        }
        return this.loependeVedtakListe;
    }

    /**
     * Gets the value of the sakstypeListe property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sakstypeListe property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSakstypeListe().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sakstyper }
     * 
     * 
     */
    public List<Sakstyper> getSakstypeListe() {
        if (sakstypeListe == null) {
            sakstypeListe = new ArrayList<Sakstyper>();
        }
        return this.sakstypeListe;
    }

    /**
     * Gets the value of the rettighetstypeListe property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rettighetstypeListe property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRettighetstypeListe().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Rettighetstyper }
     * 
     * 
     */
    public List<Rettighetstyper> getRettighetstypeListe() {
        if (rettighetstypeListe == null) {
            rettighetstypeListe = new ArrayList<Rettighetstyper>();
        }
        return this.rettighetstypeListe;
    }

}
