//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-***REMOVED***.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.09 at 11:38:41 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nav.no/melding/virksomhet/loependeYtelser/v1")
package no.nav.fo.loependeytelser;
