DROP TABLE BRUKER_DATA;

CREATE TABLE BRUKER_DATA (
  AKTOERID VARCHAR(20),
  VEILEDERIDENT VARCHAR(20),
  TILDELT_TIDSPUNKT TIMESTAMP,
  PERSONID VARCHAR(20),
  YTELSE VARCHAR(40),
  UTLOPSDATO TIMESTAMP,
  UTLOPSDATOFASETT VARCHAR(10),
  AAPMAXTID TIMESTAMP,
  AAPMAXTIDFASETT VARCHAR(10),
  PRIMARY KEY (PERSONID));