CREATE TABLE PROFILERING (
    AKTOERID VARCHAR(20) NOT NULL,
    PROFILERING_RESULTAT VARCHAR(40),
    PROFILERING_TIDSPUNKT TIMESTAMP,
    PRIMARY KEY (AKTOERID));

INSERT INTO PROFILERING (AKTOERID, PROFILERING_RESULTAT, PROFILERING_TIDSPUNKT)
    SELECT VM.AKTOERID AS AKTOERID, VM.KVALIFISERINGSGRUPPEKODE AS PROFILERING_RESULTAT, CURRENT_TIMESTAMP AS PROFILERING_TIDSPUNKT
    FROM VW_PORTEFOLJE_INFO VM
    WHERE VM.FORMIDLINGSGRUPPEKODE != 'ISERV' AND (VM.KVALIFISERINGSGRUPPEKODE = 'IVURD' OR VM.KVALIFISERINGSGRUPPEKODE = 'BKART') AND VM.AKTOERID IS NOT NULL;


UPDATE PROFILERING
    SET PROFILERING_RESULTAT = 'OPPGITT_HINDRINGER'
    WHERE PROFILERING_RESULTAT = 'BKART';

UPDATE PROFILERING
    SET PROFILERING_RESULTAT = 'ANTATT_GODE_MULIGHETER'
    WHERE PROFILERING_RESULTAT = 'IVURD';