CREATE SEQUENCE KAFKA_CONSUMER_RECORD_ID_SEQ START WITH 1;
CREATE SEQUENCE FEILET_KAFKA_MELDING_SEQ START WITH 1;

ALTER TABLE FEILET_KAFKA_MELDING
    MODIFY ID DEFAULT FEILET_KAFKA_MELDING_SEQ.nextval;
ALTER TABLE KAFKA_CONSUMER_RECORD
    MODIFY ID DEFAULT KAFKA_CONSUMER_RECORD_ID_SEQ.nextval;