CREATE SEQUENCE KAFKA_CONSUMER_RECORD_ID_SEQ START WITH 1;
CREATE SEQUENCE FEILET_KAFKA_MELDING_SEQ START WITH 1;

ALTER TABLE FEILET_KAFKA_MELDING
    MODIFY ID NUMBER(10) DEFAULT FEILET_KAFKA_MELDING_SEQ.nextval NOT NULL;
ALTER TABLE KAFKA_CONSUMER_RECORD
    MODIFY ID NUMBER(10) DEFAULT KAFKA_CONSUMER_RECORD_ID_SEQ.nextval NOT NULL;