DELETE FROM AKTOERID_TO_PERSONID a
WHERE a.ROWID > ANY (
  SELECT b.ROWID
  FROM AKTOERID_TO_PERSONID b
  WHERE a.PERSONID = b.PERSONID
        AND a.AKTOERID <> b.AKTOERID
);

ALTER TABLE AKTOERID_TO_PERSONID ADD CONSTRAINT UNIQUE_PERSONID UNIQUE (PERSONID);