CREATE TABLE BRUKER_DATA
(
    AKTOERID     VARCHAR(20) NOT NULL,
    PERSONID     VARCHAR(20),
    DAGPUTLOPUKE INTEGER,
    PERMUTLOPUKE INTEGER,
    AAPMAXTIDUKE INTEGER,
    PRIMARY KEY (AKTOERID)
);