ALTER TABLE YTELSER
    DROP (ANTALLUKERIGJEN, ANTALLPERMITTERINGUKER, ANTALLUKERIGJENUNNTAK);

ALTER TABLE YTELSER
    ADD ANTALLUKERIGJEN NUMBER(10);
ALTER TABLE YTELSER
    ADD ANTALLPERMITTERINGUKER NUMBER(10);
ALTER TABLE YTELSER
    ADD ANTALLUKERIGJENUNNTAK NUMBER(10);
