CREATE TABLE YTELSER
(
    VEDTAKID               VARCHAR(20) NOT NULL,
    AKTOERID               VARCHAR(20) NOT NULL,
    PERSONID               VARCHAR(20),
    YTELSESTYPE            VARCHAR(15),
    SAKSID                 VARCHAR(30),
    SAKSTYPEKODE           VARCHAR(10),
    RETTIGHETSTYPEKODE     VARCHAR(10),

    STARTDATO              TIMESTAMP,
    UTLOPSDATO             TIMESTAMP,
    ANTALLUKERIGJEN        INTEGER,
    ANTALLPERMITTERINGUKER INTEGER,
    ANTALLUKERIGJENUNNTAK  INTEGER,

    PRIMARY KEY (VEDTAKID)
);

CREATE INDEX AKTOERID_YTELSER_IDX ON YTELSER (AKTOERID);