apiVersion: aiven.io/v1alpha1
kind: OpenSearch
metadata:
  labels:
    team: obo
  name: opensearch-obo-veilarbportefolje
  namespace: obo
spec:
  plan: startup-4
  project: nav-dev

---

apiVersion: aiven.io/v1alpha1
kind: ServiceIntegration
metadata:
  labels:
    team: obo
  name: opensearch-obo-veilarbportefolje
  namespace: obo
spec:
  project: nav-dev
  integrationType: prometheus
  destinationEndpointId: f20f5b48-18f4-4e2a-8e5f-4ab3edb19733
  sourceServiceName: opensearch-obo-veilarbportefolje