apiVersion: aiven.io/v1alpha1
kind: OpenSearch
metadata:
  labels:
    team: obo
  name: opensearch-obo-veilarbportefolje
  namespace: obo
spec:
  plan: startup-8
  project: nav-prod

---

apiVersion: aiven.io/v1alpha1
kind: ServiceIntegration
metadata:
  labels:
    team: obo
  name: opensearch-obo-veilarbportefolje
  namespace: obo
spec:
  project: nav-prod
  integrationType: prometheus
  destinationEndpointId: 76685598-1048-4f56-b34a-9769ef747a92
  sourceServiceName: opensearch-obo-veilarbportefolje