apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: veilarbportefolje
  namespace: obo
  cluster: dev-gcp
  labels:
    team: obo
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: team-obo
  secretName: veilarbportefolje-unleash-api-token

  environment: development
