/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package no.nav.pto.veilarbportefolje.arbeidssoeker.dto.v1;

/**
 * Enkel enum som brukes til typisk 'ja', 'nei' eller 'vet ikke' svar.
 */
@org.apache.avro.specific.AvroGenerated
public enum JaNeiVetIkke implements org.apache.avro.generic.GenericEnumSymbol<JaNeiVetIkke> {
    JA, NEI, VET_IKKE;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"JaNeiVetIkke\",\"namespace\":\"no.nav.paw.arbeidssokerregisteret.api.v1\",\"doc\":\"Enkel enum som brukes til typisk 'ja', 'nei' eller 'vet ikke' svar.\",\"symbols\":[\"JA\",\"NEI\",\"VET_IKKE\"]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    @Override
    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }
}
