package no.nav.pto.veilarbportefolje.domene

import no.nav.pto.veilarbportefolje.domene.filtervalg.Filtervalg

fun getFiltervalgDefaults(): Filtervalg = Filtervalg(
    ferdigfilterListe = emptyList(),
    alder = emptyList(),
    kjonn = null,
    fodselsdagIMnd = emptyList(),
    formidlingsgruppe = emptyList(),
    servicegruppe = emptyList(),
    rettighetsgruppe = emptyList(),
    veiledere = emptyList(),
    aktiviteter = mutableMapOf(),
    tiltakstyper = emptyList(),
    manuellBrukerStatus = emptyList(),
    navnEllerFnrQuery = null,
    registreringstype = emptyList(),
    utdanning = emptyList(),
    utdanningBestatt = emptyList(),
    utdanningGodkjent = emptyList(),
    sisteEndringKategori = emptyList(),
    aktiviteterForenklet = emptyList(),
    alleAktiviteter = emptyList(),
    ulesteEndringer = null,
    cvJobbprofil = null,
    landgruppe = emptyList(),
    foedeland = emptyList(),
    tolkebehov = emptyList(),
    tolkBehovSpraak = emptyList(),
    stillingFraNavFilter = emptyList(),
    barnUnder18Aar = emptyList(),
    barnUnder18AarAlder = emptyList(),
    geografiskBosted = emptyList(),
    ensligeForsorgere = emptyList(),
    fargekategorier = emptyList(),
    gjeldendeVedtak14a = emptyList(),
    innsatsgruppeGjeldendeVedtak14a = emptyList(),
    hovedmalGjeldendeVedtak14a = emptyList(),
    ytelseAapArena = emptyList(),
    ytelseAapKelvin = emptyList(),
    ytelseTiltakspenger = emptyList(),
    ytelseTiltakspengerArena = emptyList(),
    ytelseDagpengerArena = emptyList()
)
